'use client';
import {useState} from 'react';
import {CircleCheck,TriangleAlert,Database,Download,ChevronRight} from 'lucide-react';
type Row=Record<string,any>;
const stages:Row={lock:'Uzyskanie blokady',schema:'Przygotowanie tabel',validate_schema:'Kontrola struktury',source_inventory:'Odczyt starej bazy',check_target:'Kontrola nowej bazy',copy:'Kopiowanie danych',commit:'Zatwierdzanie migracji',complete:'Zakończono'};
const reasons:Row={missing_column:'Brak wymaganej kolumny',required_field:'Brak wymaganej wartości',null_field:'Pole nie przyjmuje pustej wartości',value_length:'Nieprawidłowa długość danych',duplicate:'Powtórzona wartość klucza unikatowego',missing_table:'Brak tabeli',permissions:'Brak uprawnień bazy',busy:'Blokada bazy',encoding:'Nieobsługiwane kodowanie',validation:'Dane odrzucone przed zapisem',database:'Błąd wymagający sprawdzenia logu hostingu'};
const date=(v:string)=>v?new Date(v).toLocaleString('pl-PL'):'—';
export default function DatabaseSettings({database:d={},busy,onAction}:{database?:Row,busy:boolean,onAction:(p:Row)=>Promise<void>}){
 const [reportOpen,setReportOpen]=useState(false);
 const ready=d.namespace==='dect',status=d.status,failed=status?.state==='failed',diagnostic=status?.diagnostic;
 const collision=diagnostic?.reason==='duplicate'&&diagnostic?.index==='request_once';
 const currentProblem=failed?(diagnostic?`${reasons[diagnostic.reason]||diagnostic.reason}${diagnostic.index?' · '+diagnostic.index:''}`:status.message):status?.state==='running'?'Ostatnia próba nie ma zapisanego wyniku końcowego.':'Przeniesienie danych nie zostało jeszcze zatwierdzone.';
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='decka-raport-bazy.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="da-card da-database" aria-labelledby="database-heading">
 <div className="da-section-heading"><div><span className="da-eyebrow">BAZA DANYCH</span><h2 id="database-heading">{ready?'Baza biletów jest aktywna':'Dokończ migrację bazy'}</h2></div>{ready?<CircleCheck className="da-icon-good"/>:<TriangleAlert className="da-icon-warning"/>}</div>
 <div className={'da-system-status '+(ready?'ready':'attention')}><strong>{ready?'Migracja zakończona — dane są dostępne':'Sprzedaż i skanowanie są wstrzymane'}</strong><p>{ready?'Wtyczka korzysta z nowej bazy. Stare tabele pozostają zachowane jako archiwum.':currentProblem}</p>{!ready&&failed&&<small>Ostatnia próba: {date(status.time)} · {stages[status.step]||status.step}{status.table?' · '+status.table:''}{diagnostic?.reference?' · '+diagnostic.reference:''}</small>}</div>
 {!ready&&<><h3>Co zrobić teraz?</h3><p>{collision?'Ponów migrację. Ta wersja rozdziela powtarzające się klucze techniczne zamówień, zachowując numery zamówień, płatności i bilety.':'Uruchom migrację poniżej. System sprawdzi i przeniesie dane, a nową bazę aktywuje po poprawnym zakończeniu całej operacji.'}</p><p className="da-muted">Stare tabele pozostaną zachowane. Jeśli operacja się nie powiedzie, kopiowanie zostanie wycofane. Wtedy pobierz raport i przekaż go obsłudze.</p><button type="button" className="primary" disabled={busy} onClick={()=>onAction({operation:'database_repair'})}><Database size={17}/>{busy?'Przetwarzanie…':'Ponów migrację'}</button></>}
 <div className="da-health-row"><span>Struktura nowych tabel</span><span className={'da-badge '+(d.audit?.ok?'good':'')}>{d.audit?d.audit.ok?'Zgodna':'Wymaga sprawdzenia':'Nie sprawdzono'}</span></div><p className="da-muted">Kontrola struktury nie potwierdza przeniesienia zamówień. {d.audit?.checked_at?'Sprawdzono: '+date(d.audit.checked_at):''}</p>
 {ready&&Number(d.migration?.adjustments?.request_keys)>0&&<p>Rozdzielono klucze techniczne w {d.migration.adjustments.request_keys} zamówieniach. Numery zamówień i powiązania biletów zachowano.</p>}
 <div className="da-system-actions"><button type="button" disabled={busy} onClick={()=>onAction({operation:'database_inspect'})}>Sprawdź stan bazy</button><button type="button" onClick={download}><Download size={16}/>Pobierz raport</button></div>
 <details className="da-help" open={reportOpen} onToggle={e=>setReportOpen(e.currentTarget.open)}><summary>Szczegóły techniczne i historia</summary><dl className="da-facts"><div><dt>Wersja struktury</dt><dd>{d.version||'Nieustalona'} / wymagana {d.expected||'—'}</dd></div><div><dt>Przeniesienie danych</dt><dd>{ready?'Zatwierdzone':'Niezatwierdzone'}</dd></div>{status&&<><div><dt>Ostatnia próba</dt><dd>{date(status.time)} · {({failed:'Przerwana',complete:'Zakończona',running:'Bez wyniku końcowego'} as Row)[status.state]}</dd></div><div><dt>Etap</dt><dd>{stages[status.step]||status.step} {status.table&&'· '+status.table}</dd></div></>}</dl>
 {d.audit?.issues?.length>0&&<ul>{d.audit.issues.map((issue:string)=><li key={issue}>{issue}</li>)}</ul>}
 {(diagnostic||d.last_error)&&(()=>{const e=diagnostic||d.last_error;return <div className="da-setting-block"><h3>Zapisany błąd</h3><p className="da-muted">{ready?'Historyczny wpis — nie oznacza bieżącej awarii.':'Szczegóły ostatniego zapisanego błędu.'}</p><dl className="da-facts">{[['Kod',e.reference],['Czas',date(e.time)],['Operacja',e.table+' / '+e.operation],['Przyczyna',reasons[e.reason]||e.reason],['Pole',e.field||'—'],['Indeks',e.index||'—']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></div>})()}
 {d.inventory&&<><h3>Liczba rekordów</h3><p className="da-muted">Źródło: {d.inventory.source_prefix} · Cel: {d.inventory.target_prefix}. Po migracji archiwum nie jest aktualizowane; liczby mogą się różnić.</p><div className="da-table-wrap"><table><thead><tr><th>Tabela</th><th>Stara baza</th><th>Nowa baza</th></tr></thead><tbody>{d.inventory.tables?.map((t:Row)=><tr key={t.name}><td>{t.name}</td><td>{t.source.exists?t.source.rows+' · '+t.source.engine:'Brak'}</td><td>{t.target.exists?t.target.rows+' · '+t.target.engine:'Brak'}</td></tr>)}</tbody></table></div></>}
 {ready&&<div className="da-setting-block"><h3>Konserwacja struktury</h3><p>Użyj w przerwie sprzedaży, jeśli diagnoza wykazała niezgodności. Archiwalne zamówienia nie będą kopiowane ponownie.</p><button type="button" disabled={busy} onClick={()=>onAction({operation:'database_repair'})}>Sprawdź i napraw strukturę</button></div>}
 <p className="da-muted">Raport zawiera strukturę i stan migracji, bez danych klientów i kluczy płatności.</p><details><summary>Podgląd raportu JSON</summary><pre className="da-report">{JSON.stringify(d,null,2)}</pre></details></details>
 </section>;
}
