'use client';
type Row=Record<string,any>;
const stages:Row={lock:'Uzyskanie blokady',schema:'Przygotowanie nowych tabel',validate_schema:'Kontrola struktury nowych tabel',source_inventory:'Odczyt starych tabel',check_target:'Kontrola tabel docelowych',copy:'Kopiowanie danych',commit:'Zatwierdzanie przeniesienia',complete:'Zakończono'};
const reasons:Row={missing_column:'Brak wymaganej kolumny',required_field:'Pole wymaga wartości',null_field:'Pole nie przyjmuje NULL',value_length:'Nieprawidłowa długość danych',duplicate:'Powtórzona wartość indeksu unikatowego',missing_table:'Brak tabeli',permissions:'Brak uprawnień bazy',busy:'Blokada bazy',encoding:'Nieobsługiwane kodowanie',validation:'Dane odrzucone przed zapisem',database:'Błąd bazy wymagający sprawdzenia logu hostingu'};
export default function DatabaseSettings({database:d={},busy,onAction}:{database?:Row,busy:boolean,onAction:(p:Row)=>Promise<void>}){
 const ready=d.namespace==='dect',status=d.status,diagnostic=status?.diagnostic||d.last_error;
 return <section className="da-space" aria-labelledby="database-heading"><h2 id="database-heading">Baza danych i migracja</h2>
 <div className={'da-alert '+(ready?'':'error')}><strong>{ready?'Nowa baza jest aktywna':'Przenoszenie danych nie zostało zatwierdzone'}</strong><p>{ready?'Wtyczka korzysta z tabel dect_ poprzedzonych prefiksem WordPressa. Dostępność sprzedaży zależy również od ustawień meczów i płatności.':'Zakup i skanowanie są wstrzymane, aby nie używać niepełnego zestawu danych. Poprawna struktura tabel sama nie potwierdza ukończenia migracji.'}</p></div>
 <p>Wersja zapisanej struktury: <b>{d.version||'nieustalona'}</b>. Wersja wymagana: <b>{d.expected||'—'}</b>.</p>
 {status&&<div className="da-db-diagnostic"><h3>Ostatnia próba migracji</h3><p>Wynik: <b>{({failed:'Przerwana',complete:'Zakończona',running:'Rozpoczęta — brak zapisanego wyniku końcowego'} as Row)[status.state]||'Nieustalony'}</b></p><p>Etap: {stages[status.step]||status.step}{status.table?' · tabela '+status.table:''}</p><p>Czas: {new Date(status.time).toLocaleString('pl-PL')}</p><p>{status.message}</p>{status.state==='running'&&<p>Ten wpis nie potwierdza, że proces nadal trwa. Po przerwanym żądaniu możesz ponowić migrację; blokada bazy chroni przed równoczesnym kopiowaniem.</p>}</div>}
 {!status&&d.error&&<p className="da-alert error">{d.error} To zapis ze starszej wersji. Ponów migrację poniższym przyciskiem, aby otrzymać dokładny etap i przyczynę.</p>}
 <div className="da-db-diagnostic"><h3>1. Diagnoza bez przenoszenia danych</h3><p>Sprawdza pola i indeksy nowych tabel oraz liczbę rekordów w starych i nowych tabelach. Nie kopiuje zamówień, nie usuwa danych i nie odblokowuje sprzedaży. Aktualizuje wyłącznie raport diagnostyczny.</p><button type="button" disabled={busy} onClick={()=>onAction({operation:'database_inspect'})}>Sprawdź strukturę i stan danych</button></div>
 <div className="da-db-diagnostic"><h3>2. Naprawa struktury i przeniesienie danych</h3><p>Przygotowuje tabele dect_, sprawdza ich strukturę, a następnie przenosi dane ze starych tabel decka_. Nową bazę aktywuje dopiero po sprawdzeniu i zatwierdzeniu całej operacji. Jeśli migracja już się udała, nie kopiuje archiwum ponownie.</p><p>Uruchom w przerwie sprzedaży i skanowania. Stare tabele pozostają zachowane. W razie błędu kopiowanie jest wycofywane, a poniżej pojawia się konkretny etap i przyczyna. Nie usuwaj ręcznie tabel.</p><button type="button" className="primary" disabled={busy} onClick={()=>onAction({operation:'database_repair'})}>{ready?'Sprawdź i napraw aktywną bazę':'Napraw strukturę i ponów migrację'}</button>{busy&&<p role="status">Trwa operacja w panelu. Poczekaj na jej wynik.</p>}</div>
 {d.audit&&<div className="da-db-diagnostic"><h3>Wynik kontroli struktury</h3><p>{d.audit.ok?'Pola i indeksy nowych tabel są zgodne. To wynik kontroli struktury, nie potwierdzenie przeniesienia danych.':'Wykryto niezgodności struktury:'}</p>{d.audit.issues?.map((issue:string)=><p key={issue}>{issue}</p>)}<p>Sprawdzono: {new Date(d.audit.checked_at).toLocaleString('pl-PL')}</p></div>}
 {d.inventory&&<div className="da-db-diagnostic"><h3>Dane w starych i nowych tabelach</h3><p>Źródło: {d.inventory.source_prefix} · Cel: {d.inventory.target_prefix}. Same równe liczby nie potwierdzają zgodności zawartości. Po migracji stare tabele są archiwum i nie przybywają w nich nowe zakupy.</p><div style={{overflowX:'auto'}}><table><thead><tr><th>Tabela</th><th>Stara baza</th><th>Nowa baza</th></tr></thead><tbody>{d.inventory.tables?.map((t:Row)=><tr key={t.name}><td>{t.name}</td><td>{t.source.exists?t.source.rows+' rekordów · '+t.source.engine:'Brak tabeli'}</td><td>{t.target.exists?t.target.rows+' rekordów · '+t.target.engine:'Brak tabeli'}</td></tr>)}</tbody></table></div></div>}
 {diagnostic&&<div className="da-db-diagnostic"><h3>Ostatni zarejestrowany błąd bazy</h3><p>Kod: <b>{diagnostic.reference}</b> · {new Date(diagnostic.time).toLocaleString('pl-PL')}</p><p>Etap zapisu: {diagnostic.table} / {diagnostic.operation}</p><p>Przyczyna: {reasons[diagnostic.reason]||diagnostic.reason}</p>{diagnostic.field&&<p>Pole: {diagnostic.field}</p>}{diagnostic.index&&<p>Indeks: {diagnostic.index}</p>}<small>To historyczny wpis. Po udanej naprawie pozostaje widoczny i nie oznacza, że błąd nadal występuje.</small></div>}
 <details><summary>Raport techniczny do przekazania obsłudze</summary><p>Raport zawiera strukturę, liczby rekordów i etap błędu, bez wierszy klientów i kluczy płatności.</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontSize:12}}>{JSON.stringify(d,null,2)}</pre></details>
 </section>;
}
