'use client';
import {useState} from 'react';

export default function SystemTools({api,archive,report,canReset}:{api:(path:string,body?:Record<string,unknown>)=>Promise<any>;archive:string;report:string;canReset:boolean}){
 const [challenge,setChallenge]=useState<any>(null),[confirmation,setConfirmation]=useState(''),[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function begin(){setBusy(true);setMessage('');try{setChallenge(await api('action',{operation:'reset_challenge'}))}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function reset(){setBusy(true);setMessage('');try{const r=await api('action',{operation:'reset_system',token:challenge.token,confirmation,answer:Number(answer)});setMessage(r.message);setChallenge(null);setConfirmation('');setAnswer('')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <section className="da-card"><h2>Archiwum i reset systemu</h2><p>Pobierz pełną kopię danych przed zmianami sezonu lub wyczyszczeniem systemu.</p><div className="da-system-actions"><a className="da-install" href={archive}>Pobierz archiwum bazy</a><a className="da-install" href={report}>Pobierz pełny raport PDF</a></div><hr/>{!challenge?<><h3>Przywróć stan początkowy</h3><p className="da-muted">Usuwa mecze, zamówienia, bilety, blokady, promocje i logi. Wymaga dwóch oddzielnych potwierdzeń.</p><button type="button" className="danger" disabled={!canReset||busy} onClick={begin}>Rozpocznij reset</button></>:<div className="da-reset"><h3>Drugie potwierdzenie</h3><label className="da-field">Wpisz dokładnie: USUŃ DANE<input value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><label className="da-field">Oblicz: {challenge.question}<input type="number" value={answer} onChange={e=>setAnswer(e.target.value)}/></label><div className="da-system-actions"><button type="button" className="danger" disabled={busy||confirmation!=='USUŃ DANE'||answer===''} onClick={reset}>Trwale wyczyść system</button><button type="button" disabled={busy} onClick={()=>setChallenge(null)}>Anuluj</button></div></div>}{message&&<p role="status" className="da-alert">{message}</p>}</section>
}
