import {chromium,launchOptions} from './browser.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser=await chromium.launch(launchOptions);
const page=await browser.newPage({viewport:{width:1500,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.WP_URL||'http://127.0.0.1:9410';fs.mkdirSync('tests/artifacts',{recursive:true});
const anon=await page.request.get(base+'/wp-json/decka/v1/admin/bootstrap');assert.equal(anon.status(),401);assert.equal((await page.request.post(base+'/wp-json/decka/v1/admin/updates/check',{data:{}})).status(),401);
await page.goto(base+'/wp-login.php');await page.locator('#user_login').fill('admin');await page.locator('#user_pass').fill('password');await page.locator('#wp-submit').click();await page.waitForURL(/wp-admin/);
await page.goto(base+'/wp-admin/admin.php?page=decka-bilety');const frame=page.frameLocator('.decka-admin-frame');await frame.getByRole('heading',{name:'Pulpit',exact:true}).waitFor();await frame.getByText('Brak zgłoszonych problemów z zamówieniami.').waitFor();
const f=page.frames().find(f=>f.url().includes('view=admin'));
async function api(path,body){return f.evaluate(async({path,body})=>{const c=window.DECKA;const r=await fetch(c.api+'admin/'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-WP-Nonce':c.nonce},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json()};},{path,body});}
const boot=await api('bootstrap');assert.equal(boot.status,200,JSON.stringify(boot));assert.equal(boot.data.seats.seats.length,340);assert.ok(!('test_secret' in boot.data.settings));const eid=boot.data.events[0].id;
await page.screenshot({path:'tests/artifacts/admin-dashboard.png',fullPage:true});
for(const name of ['Mecze','Plan hali','Zamówienia','Bilety i vouchery','Mini-karnety','Promocje i kody','Kibice','Wejścia i bileterzy','Raporty','Ustawienia']){await frame.locator('.da-nav').getByRole('button',{name,exact:true}).click();await frame.getByRole('heading',{name,exact:true}).waitFor();}
await frame.getByLabel('Bilet normalny (zł)').fill('25');await frame.getByLabel('Bilet ulgowy (zł)').fill('15');await frame.getByRole('button',{name:'Zapisz zmiany'}).click();await frame.getByText('Zapisano zmiany.').waitFor();assert.equal((await api('bootstrap')).data.settings.normal,2500);
await frame.locator('.da-nav').getByRole('button',{name:'Mecze',exact:true}).click();await frame.getByRole('button',{name:'Dodaj mecz'}).click();await frame.getByLabel('Przeciwnik',{exact:true}).fill('Test panelu');await frame.getByLabel('Hala',{exact:true}).fill('Pelplin');await frame.getByLabel('Termin meczu (Warszawa)').fill('2027-01-10T18:00');await frame.getByLabel('Sprzedaż otwarta').check();await frame.getByRole('button',{name:'Zapisz i zatwierdź'}).click();await frame.getByRole('dialog').waitFor({state:'hidden'});const games=(await api('bootstrap')).data.events;const newEvent=games.find(e=>e.opponent==='Test panelu');assert.ok(newEvent);assert.equal(newEvent.starts_at,'2027-01-10 17:00:00');
await frame.locator('.da-nav').getByRole('button',{name:'Mini-karnety',exact:true}).click();await frame.getByRole('button',{name:'Nowy mini-karnet'}).click();await frame.getByLabel('Nazwa pakietu').fill('Dwa mecze');await frame.getByLabel('Cena normalna pakietu (zł)').fill('40');await frame.getByLabel('Cena ulgowa pakietu (zł)').fill('25');await frame.locator('input[name="event_ids"]').first().check();await frame.locator('input[name="event_ids"]').last().check();await frame.getByRole('button',{name:'Zapisz i zatwierdź'}).click();await frame.getByRole('dialog').waitFor({state:'hidden'});assert.equal(Number((await api('bootstrap')).data.offers[0].normal_price),4000);
await frame.locator('.da-nav').getByRole('button',{name:'Promocje i kody',exact:true}).click();await frame.getByRole('button',{name:'Nowy kod'}).click();await frame.getByLabel('Kod',{exact:true}).fill('TEST'+Date.now());await frame.getByLabel('Wartość rabatu').fill('20');await frame.getByRole('button',{name:'Zapisz i zatwierdź'}).click();await frame.getByRole('dialog').waitFor({state:'hidden'});assert.equal(Number((await api('bootstrap')).data.promos[0].value),20);
await frame.getByLabel('Filtr meczu').selectOption(String(eid));await frame.locator('.da-nav').getByRole('button',{name:'Plan hali',exact:true}).click();await frame.getByRole('button',{name:/Sektor B/}).click();await frame.getByRole('button',{name:'66 wolne',exact:true}).click();await frame.getByRole('button',{name:'Zablokuj dla organizatora'}).click();await frame.getByLabel('Powód (do historii operacji)').fill('Test blokady');await frame.getByRole('button',{name:'Zapisz i zatwierdź'}).click();await frame.getByRole('dialog').waitFor({state:'hidden'});assert.equal((await api('inventory?event='+eid)).data.rows[0].order_id,'0');
await frame.getByRole('button',{name:'66 Blokada',exact:true}).waitFor();await frame.getByRole('button',{name:'66 Blokada',exact:true}).click();await frame.getByRole('button',{name:'Zwolnij ręczne blokady'}).click();await frame.getByRole('button',{name:'Zapisz i zatwierdź'}).click();await frame.getByRole('dialog').waitFor({state:'hidden'});assert.equal((await api('inventory?event='+eid)).data.rows.length,0);
await frame.locator('.da-nav').getByRole('button',{name:'Bilety i vouchery',exact:true}).click();await frame.getByRole('button',{name:'Wystaw voucher'}).click();await frame.getByLabel('E-mail odbiorcy').fill('admin-test@example.test');await frame.getByRole('button',{name:'66 wolne',exact:true}).click();await frame.getByRole('button',{name:'Utwórz i wyślij voucher'}).click();await frame.getByRole('dialog').waitFor({state:'hidden'});const tickets=(await api('tickets')).data.rows;assert.equal(tickets[0].email,'admin-test@example.test');const ticket=tickets[0];
assert.equal((await api('action',{operation:'seat_release',event_id:eid,seats:['66']})).status,400);
await frame.getByRole('button',{name:'Zamówienie',exact:true}).first().click();await frame.getByRole('heading',{name:'Zamówienie #'+ticket.order_id}).waitFor();const pdf=await page.request.get(await frame.getByRole('link',{name:'Pobierz bilety PDF'}).getAttribute('href'));assert.equal(pdf.status(),200);assert.ok((await pdf.body()).subarray(0,5).toString()==='%PDF-');await frame.getByRole('button',{name:'Zamknij',exact:true}).click();
await frame.getByRole('button',{name:'Unieważnij',exact:true}).first().click();await frame.getByRole('button',{name:'Zapisz i zatwierdź'}).click();await frame.getByRole('dialog').waitFor({state:'hidden'});assert.equal((await api('tickets')).data.rows[0].status,'revoked');
const csv=await page.request.get(boot.data.links.csv);assert.equal(csv.status(),200);assert.ok((await csv.text()).includes('admin-test@example.test'));
await frame.locator('.da-nav').getByRole('button',{name:'Ustawienia',exact:true}).click();await frame.getByRole('button',{name:'System',exact:true}).click();await frame.getByRole('button',{name:'Sprawdź aktualizacje teraz'}).click();await frame.getByRole('button',{name:'Sprawdź aktualizacje teraz'}).waitFor();await page.waitForFunction(()=>true);await frame.getByText('Zakończono sprawdzanie aktualizacji.').waitFor({timeout:90000});const update=(await api('bootstrap')).data.updater;assert.ok(['no_release','error','current','available'].includes(update.status));console.log('Live GitHub check:',update.status,update.message);
// Environment inventory is isolated and unauthorized staff cannot access administration.
const settings=(await api('bootstrap')).data.settings;
assert.equal((await api('action',{operation:'settings',...settings,mode:'live'})).status,200);
assert.equal((await api('inventory?event='+eid)).data.rows.length,0);
assert.equal((await api('action',{operation:'settings',...settings,mode:'test'})).status,200);
const gatePage=await browser.newPage();await gatePage.goto(base+'/wp-login.php');await gatePage.locator('#user_login').fill('bileter');await gatePage.locator('#user_pass').fill('Local-Testing-Only-123');await gatePage.locator('#wp-submit').click();await gatePage.waitForURL(/wp-admin/);await gatePage.goto(base+'/wp-admin/admin-post.php?action=decka_app&view=gate');await gatePage.getByRole('heading',{name:'Decka · skaner',exact:true}).waitFor();
const denied=await gatePage.evaluate(async()=>{const c=window.DECKA;return Promise.all(['bootstrap','updates/check'].map(async p=>{const r=await fetch(c.api+'admin/'+p,{method:p==='bootstrap'?'GET':'POST',headers:{'X-WP-Nonce':c.nonce,'Content-Type':'application/json'},body:p==='bootstrap'?undefined:'{}'});return r.status}));});assert.deepEqual(denied,[403,403]);await gatePage.close();
await page.screenshot({path:'tests/artifacts/admin-settings.png',fullPage:true});await frame.locator('.da-nav').getByRole('button',{name:'Pulpit',exact:true}).click();await page.screenshot({path:'tests/artifacts/admin-dashboard.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'tests/artifacts/admin-mobile.png',fullPage:true});assert.ok(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no mobile page overflow');assert.deepEqual(errors,[]);
console.log('PASS admin: 11 pages, settings, event/timezone, offer, promo, seat block/release, voucher, PDF, revocation, protected inventory, CSV, GitHub check, mobile, no JS errors');await browser.close();
