import {chromium,launchOptions} from './browser.mjs';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve('frontend/out'),seats=JSON.parse(fs.readFileSync('plugin/data/seats.json'));
const browser=await chromium.launch(launchOptions),page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('popup',p=>p.close());
const events=[{id:1,opponent:'Test kasjera',starts_at:'2030-10-10 16:00:00',venue:'Pelplin',sale_open:1,normal_price:2500,reduced_price:1500}];let cart={order_id:1,items:[],total:0},sold=new Set(['68']);
await page.route('http://decka-cashier.test/**',async route=>{const u=new URL(route.request().url());let json;const body=route.request().postDataJSON?.()||{};
 if(u.pathname==='/api/catalog')json={mode:'test',normal:2500,reduced:1500,seats,events,offers:[],registration:true};
 if(u.pathname==='/api/cashier/events')json=events;
 if(u.pathname==='/api/availability')json={seats:[...sold].map(seat_id=>({seat_id,state:'cashier'})).concat(cart.items.map(i=>({seat_id:i.seat_id,state:'cashier_hold'})))};
 if(u.pathname==='/api/cashier/cart')json=cart;
 if(u.pathname==='/api/cashier/hold'){const amount=body.kind==='free'?0:body.kind==='reduced'?1500:2500;cart.items=cart.items.filter(i=>i.seat_id!==body.seat_id).concat({seat_id:body.seat_id,kind:body.kind,amount});cart.total=cart.items.reduce((n,i)=>n+i.amount,0);json=cart;}
 if(u.pathname==='/api/cashier/release'){cart.items=cart.items.filter(i=>i.seat_id!==body.seat_id);cart.total=cart.items.reduce((n,i)=>n+i.amount,0);json=cart;}
 if(u.pathname==='/api/cashier/confirm'){for(const i of cart.items)sold.add(i.seat_id);json={order_id:2,number:'DK-TEST-2',pdf:'http://decka-cashier.test/ticket.pdf'};cart={order_id:0,items:[],total:0};}
 if(u.pathname==='/api/cashier/exchange'){sold.delete(body.old_seat);sold.add(body.new_seat);json={message:'Miejsce zostało wymienione.',pdf:'http://decka-cashier.test/ticket.pdf'};}
 if(u.pathname==='/ticket.pdf')return route.fulfill({contentType:'application/pdf',body:'%PDF-1.4\n%%EOF'});
 if(json)return route.fulfill({json});
 const file=path.join(root,u.pathname==='/'?'index.html':u.pathname);if(!fs.existsSync(file)||fs.statSync(file).isDirectory())return route.fulfill({status:404,body:''});let content=fs.readFileSync(file),type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream';if(type==='text/html')content=Buffer.from(content.toString().replace('<head>','<head><script>window.DECKA={api:"http://decka-cashier.test/api/",nonce:"test",view:"cashier",user:{name:"Kasjer",email:"kasjer@example.test",gate:false,cashier:true,admin:false},shopUrl:"/bilety/",cashierUrl:"/kasjer/"}</script>'));return route.fulfill({body:content,contentType:type});
});
await page.goto('http://decka-cashier.test/');await page.getByRole('button',{name:/Sprzedaż biletów/}).click();assert.equal(await page.locator('.cashier-shell').count(),1);assert.equal(await page.locator('header:visible').count(),0);await page.getByRole('button',{name:'Powiększ sektor B'}).click();await page.getByRole('button',{name:'Sektor B, rząd 1, miejsce 66',exact:true}).click();await page.getByRole('dialog',{name:'Wybierz rodzaj biletu'}).waitFor();await page.getByRole('button',{name:/Ulgowy/}).click();await page.getByText('Sektor B · Rząd 1 · Miejsce 66',{exact:true}).waitFor();await page.getByLabel('Rodzaj biletu miejsce 66').selectOption('normal');await page.getByRole('button',{name:'Potwierdź i drukuj bilety'}).click();const summary=page.getByRole('dialog',{name:'Podsumowanie zakończonej sprzedaży'});await summary.waitFor();assert.match(await summary.innerText(),/Do zapłaty: 25,00/);assert.match(await summary.innerText(),/Sektor B · Rząd 1 · Miejsce 66/);await page.getByRole('button',{name:/Zakończ sprzedaż/}).click();await page.getByRole('button',{name:/Wymiana biletów/}).click();await page.getByRole('button',{name:'Powiększ sektor B'}).click();await page.getByRole('button',{name:/Sektor B, rząd 1, miejsce 68/}).click();await page.getByRole('button',{name:/Sektor B, rząd 1, miejsce 69/}).click();assert.match(await page.locator('.cashier-exchange-bar').innerText(),/Poprzednie miejsce: 68/);assert.match(await page.locator('.cashier-exchange-bar').innerText(),/Nowe miejsce: 69/);await page.getByRole('button',{name:'Zatwierdź zmianę'}).click();await page.getByText('Miejsce zostało wymienione.').waitFor();assert.equal(await page.getByRole('button',{name:'Powrót do widoku całej hali'}).count(),1);assert.equal(await page.getByRole('button',{name:'Menu'}).evaluate(e=>getComputedStyle(e).borderBottomColor),'rgb(207, 37, 25)');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await browser.close();console.log('PASS cashier UI: full-screen shell, ticket-kind popup/change, large sale summary, finish reset, exchange bar/confirmation, hall return and mobile containment');
