import {chromium,launchOptions} from './browser.mjs';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve('frontend/out'),seats=JSON.parse(fs.readFileSync('plugin/data/seats.json'));
const browser=await chromium.launch(launchOptions),page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
const games=[1,2].map(id=>({id,opponent:'Przeciwnik '+id,starts_at:'2030-10-10 16:00:00',venue:'Pelplin',sale_open:1,normal_price:2500,reduced_price:1500,opponent_logo:'/logo.png'}));let allow=true,download=false,paid=true;
await page.route('http://decka-ui.test/**',async route=>{const u=new URL(route.request().url());let json;
if(u.pathname==='/api/catalog')json={mode:'test',normal:2500,reduced:1500,seats,events:games,offers:[{id:1,name:'Dwa mecze',event_ids:'[1,2]',normal_price:4000,reduced_price:2500,promos_allowed:allow}],registration:true,main_sponsor_image_url:'/logo.png',sponsor_image_url:'/mini-karnet.png'};
if(u.pathname==='/api/availability')json={seats:[{seat_id:'66',state:'hidden'},{seat_id:'67',state:'camera'},{seat_id:'68',state:'busy'}]};
if(u.pathname==='/api/quote')json={before:4000,total:3600,discount:400,percent:10};
if(u.pathname==='/api/orders')json=[{id:1,number:'Z-ABCDEF1234567890',offer_id:1,status:paid?'paid':'pending',mode:'test',total:3600,download:'/old-download',items:games.map(g=>({seat_id:'69',kind:'normal',opponent:g.opponent,starts_at:g.starts_at}))}];
if(u.pathname==='/api/orders/1/cancel'){paid=true;json={ok:true,status:'paid'};}
if(u.pathname==='/api/orders/1/download'){download=true;json={url:'http://decka-ui.test/new.pdf'};}
if(u.pathname==='/new.pdf')return route.fulfill({contentType:'application/pdf',headers:{'Content-Disposition':'attachment; filename=ticket.pdf'},body:'%PDF-1.4\n%%EOF'});
if(json)return route.fulfill({json});
const file=path.join(root,u.pathname==='/'?'index.html':u.pathname);if(!fs.existsSync(file)||fs.statSync(file).isDirectory())return route.fulfill({status:404,body:''});let body=fs.readFileSync(file);const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream';if(type==='text/html')body=Buffer.from(body.toString().replace('<head>','<head><script>window.DECKA={api:"http://decka-ui.test/api/",nonce:"test",user:{name:"Jan",email:"jan@example.test",profile:{first_name:"Jan",last_name:"Test"}},shopUrl:"/bilety/",googleLogin:"/google"}</script>'));return route.fulfill({body,contentType:type});});
await page.goto('http://decka-ui.test/');await page.locator('.package-tile').waitFor();assert.equal(await page.locator('.steps,.benefits').count(),0);assert.equal(await page.locator('.hero p').isVisible(),false);assert.equal(await page.locator('.brand-name').isVisible(),false);assert.equal(await page.locator('.package-prices .saving del').count(),2);assert.equal(await page.locator('.package-tile .opponent-line img').count(),2);assert.match(await page.locator('.package-tile .saving').first().innerText(),/20%/);await page.screenshot({path:'tests/artifacts/commerce-tiles-mobile.png',fullPage:true});
assert.equal(await page.locator('.shop-sponsors img').count(),2);assert.equal(await page.locator('.shop-sponsors img').first().getAttribute('src'),'/logo.png');await page.locator('.package-tile').click();assert.equal(await page.locator('.selected-product .package-prices .saving del').count(),2);assert.equal(await page.locator('.package-match-list .versus-icon').count(),2);assert.equal(await page.locator('button.back').first().evaluate(e=>getComputedStyle(e).color),'rgb(255, 255, 255)');assert.equal(await page.locator('button.back').first().evaluate(e=>getComputedStyle(e).borderBottomColor),'rgb(207, 37, 25)');await page.getByText('NAZWA KARNETU',{exact:true}).waitFor();assert.equal(await page.locator('.sector-title-mobile').first().isVisible(),true);assert.equal(await page.locator('.sector-title-mobile').first().textContent(),'B');assert.equal(await page.locator('.sector-divider').count(),2);await page.screenshot({path:'tests/artifacts/mobile-hall-overview.png',fullPage:true});await page.getByRole('button',{name:'Powiększ sektor B'}).click();assert.equal(await page.getByRole('button',{name:'Sektor B, rząd 1, miejsce 66',exact:true}).count(),0);assert.equal(await page.locator('button.camera-seat').count(),1);assert.ok(await page.locator('button.camera-seat').isDisabled());await page.getByRole('button',{name:'Sektor B, rząd 1, miejsce 69',exact:true}).click();assert.equal(await page.locator('.seat.chosen').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(25, 86, 157)');
await page.getByPlaceholder('Wpisz kod').fill('TEST10');await page.locator('.total .saving span').waitFor();assert.match(await page.locator('.total').innerText(),/10%/);assert.equal(await page.locator('.payment-brands img').count(),2);await page.screenshot({path:'tests/artifacts/commerce-selection-mobile.png',fullPage:true});
await page.getByRole('button',{name:'Moje konto'}).click();await page.getByRole('heading',{name:'Dane kontaktowe'}).waitFor();await page.locator('.account-order-heading').waitFor();assert.match(await page.locator('.account-order-heading').innerText(),/Przeciwnik 1/);assert.equal(await page.locator('.account-order').evaluate(e=>e.open),false);await page.locator('.account-order-heading').click();await page.locator('.account-ticket').waitFor();assert.equal(await page.locator('.account-ticket').count(),1);assert.equal(await page.locator('.account-ticket li').count(),2);assert.match(await page.locator('summary .order-status').innerText(),/Opłacone/);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'tests/artifacts/commerce-account-mobile.png',fullPage:true});const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Pobierz bilety PDF'}).click();await dl;assert.equal(download,true);
paid=false;await page.reload();await page.getByRole('button',{name:'Moje konto'}).click();await page.locator('.account-order-heading').click();await page.getByRole('button',{name:'Anuluj i zwolnij miejsca'}).click();await page.getByText('Płatność została już potwierdzona. Twoje bilety są dostępne.',{exact:true}).waitFor();
allow=false;await page.reload();await page.locator('.package-tile').click();await page.getByText('Dla tego mini-karnetu nie można zastosować kodów rabatowych.').waitFor();assert.equal(await page.getByPlaceholder('Wpisz kod').count(),0);assert.deepEqual(errors,[]);await browser.close();console.log('PASS commerce UI: package games/logos/savings, hidden/camera seats, blue selection, live discount, payment marks, contact account, grouped tickets, fresh PDF link, no-code package');
