import {chromium,launchOptions} from './browser.mjs';import assert from 'node:assert/strict';
const browser=await chromium.launch(launchOptions);const page=await browser.newPage();const base=process.env.WP_URL||'http://127.0.0.1:9411';await page.goto(base+'/wp-login.php');await page.locator('#user_login').fill('admin');await page.locator('#user_pass').fill('password');await page.locator('#wp-submit').click();await page.waitForURL(/wp-admin/);await page.goto(base+'/wp-admin/admin-post.php?action=decka_app&view=admin');await page.locator('.da-metrics').waitFor();
const api=(path,body)=>page.evaluate(async({path,body})=>{const c=window.DECKA;const r=await fetch(c.api+'admin/'+path,{method:body?'POST':'GET',headers:{'X-WP-Nonce':c.nonce,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return{status:r.status,data:await r.json()};},{path,body});
let b=(await api('bootstrap')).data;await api('action',{operation:'settings',...b.settings,normal:2500,reduced:1500});const g=b.events[0],seat=b.seats.seats.find(s=>s.id==='90');let r=await api('action',{operation:'settings',...b.settings,normal:2700,reduced:1700});assert.equal(r.status,200);b=(await api('bootstrap')).data;assert.ok(b.events.every(e=>Number(e.normal_price)===2700&&Number(e.reduced_price)===1700));
r=await api('action',{operation:'event',...g,starts_at:null,gate_open:null,gate_close:null,sale_open:false,normal_price:3300,reduced_price:2200});assert.equal(r.status,200,JSON.stringify(r));b=(await api('bootstrap')).data;assert.equal(Number(b.events.find(e=>e.id===g.id).normal_price),3300);assert.ok(b.events.filter(e=>e.id!==g.id).every(e=>Number(e.normal_price)===2700));
r=await api('action',{operation:'seat_block',event_id:0,seats:[seat.id]});assert.equal(r.status,200,JSON.stringify(r));let inv=(await api('inventory?event=0')).data.rows;assert.equal(inv.filter(i=>i.seat_id===seat.id).length,b.events.length);r=await api('action',{operation:'seat_release',event_id:0,seats:[seat.id]});assert.equal(r.status,200);const occupied=inv.find(i=>Number(i.order_id)>0);assert.ok(occupied);r=await api('action',{operation:'seat_block',event_id:0,seats:[seat.id,occupied.seat_id]});assert.equal(r.status,400);inv=(await api('inventory?event=0')).data.rows;assert.equal(inv.filter(i=>i.seat_id===seat.id).length,0,'failed bulk operation rolls back all events');assert.ok(inv.some(i=>i.seat_id===occupied.seat_id&&i.order_id===occupied.order_id));
assert.ok((await api('gate')).data.users.some(u=>u.email==='gate@example.test'));assert.ok((await api('gate')).data.users.some(u=>u.administrator));
const upload=await page.request.post(base+'/wp-json/decka/v1/admin/media',{headers:{'X-WP-Nonce':await page.evaluate(()=>window.DECKA.nonce)},multipart:{image:{name:'match.png',mimeType:'image/png',buffer:await (await import('node:fs/promises')).readFile('frontend/public/logo.png')}}});assert.equal(upload.status(),200,await upload.text());const media=await upload.json();assert.ok(media.id&&media.url);
// Restore prices and schedule, keep image to check PDF rendering through existing browser test.
r=await api('action',{operation:'event',...g,starts_at:new Date(Date.now()+86400000).toLocaleString('sv-SE',{timeZone:'Europe/Warsaw'}).replace(' ','T').slice(0,16),gate_open:new Date(Date.now()-3600000).toLocaleString('sv-SE',{timeZone:'Europe/Warsaw'}).replace(' ','T').slice(0,16),gate_close:new Date(Date.now()+3600000).toLocaleString('sv-SE',{timeZone:'Europe/Warsaw'}).replace(' ','T').slice(0,16),sale_open:true,image_id:media.id,normal_price:2500,reduced_price:1500});assert.equal(r.status,200,JSON.stringify(r));r=await api('action',{operation:'settings',...b.settings,normal:2500,reduced:1500});assert.equal(r.status,200);console.log('PASS extended admin: global/individual prices, atomic all-event blocks protect existing orders, gate staff listing, match image upload');await browser.close();
