<?php
require __DIR__.'/../plugin/includes/identity.php';require __DIR__.'/../plugin/includes/wallet.php';
function wp_json_encode($v,$flags=0){return json_encode($v,$flags);}function home_url(){return 'https://example.test';}function wp_date($f,$t,$tz){return (new DateTimeImmutable('@'.$t))->setTimezone($tz)->format($f);}
class Decka_DB{static array $settings=[];static function settings(){return self::$settings;}static function seats(){return ['seats'=>[['id'=>'66','sector'=>'B','row'=>1,'number'=>66]]];}}class Decka_Stripe{static function decrypt($v){return $v;}}
$checks=0;function check($ok,$name){global $checks;if(!$ok)throw new Exception($name);$checks++;echo "PASS $name\n";}function rejects($fn,$name){try{$fn();}catch(Throwable $e){check(true,$name);return;}check(false,$name);}
$key=openssl_pkey_new(['private_key_bits'=>2048,'private_key_type'=>OPENSSL_KEYTYPE_RSA]);if(!$key){$private=file_get_contents(__DIR__.'/artifacts/test-signing-key.pem');$key=openssl_pkey_get_private($private);}else{openssl_pkey_export($key,$private);}$public=openssl_pkey_get_details($key)['key'];$now=time();$claims=['aud'=>'client','iss'=>'https://accounts.google.com','sub'=>'user-1','nonce'=>'one-time-nonce','exp'=>$now+300,'iat'=>$now,'email_verified'=>true,'email'=>'test@example.test'];
$b64=fn($s)=>rtrim(strtr(base64_encode($s),'+/','-_'),'=');$sign=function($claims,$alg='RS256')use($b64,$private){$raw=$b64(json_encode(['alg'=>$alg,'kid'=>'key-1'])).'.'.$b64(json_encode($claims));openssl_sign($raw,$signature,$private,OPENSSL_ALGO_SHA256);return $raw.'.'.$b64($signature);};
check(Decka_Identity::verify($sign($claims),'client','one-time-nonce',['key-1'=>$public],$now)['sub']==='user-1','Google valid signed identity');
foreach(['aud'=>'other','iss'=>'https://attacker.test','exp'=>$now-1,'nonce'=>'replayed','email_verified'=>false,'azp'=>'other'] as $k=>$v){$bad=$claims;$bad[$k]=$v;rejects(fn()=>Decka_Identity::verify($sign($bad),'client','one-time-nonce',['key-1'=>$public],$now),'Reject incorrect '.$k);}
rejects(fn()=>Decka_Identity::verify($sign($claims,'none'),'client','one-time-nonce',['key-1'=>$public],$now),'Reject algorithm substitution');rejects(fn()=>Decka_Identity::verify($sign($claims),'client','one-time-nonce',[],$now),'Reject unknown signing key');
Decka_DB::$settings=['google_wallet_issuer'=>'123','google_wallet_credentials'=>json_encode(['client_email'=>'service@example.test','private_key'=>$private])];$t=(object)['id'=>5,'seat_id'=>'66','opponent'=>'Test team','starts_at'=>null,'venue'=>'Test hall'];$doc=['ticket'=>$t,'events'=>[$t],'package'=>true,'token'=>'DK2.5.'.str_repeat('a',64)];$url=Decka_Wallet::google($doc,(object)['mode'=>'test']);$jwt=substr($url,strlen('https://pay.google.com/gp/v/save/'));$parts=explode('.',$jwt);check(openssl_verify($parts[0].'.'.$parts[1],base64_decode(strtr($parts[2],'-_','+/')),$public,OPENSSL_ALGO_SHA256)===1,'Google Wallet JWT signature');$payload=json_decode(base64_decode(strtr($parts[1],'-_','+/')),true);check($payload['payload']['genericObjects'][0]['barcode']['value']===$doc['token'],'Wallet preserves package QR');check(str_contains($payload['payload']['genericObjects'][0]['textModulesData'][0]['body'],'Termin do potwierdzenia'),'Wallet retains unknown date');echo "TOTAL $checks identity and wallet checks\n";
// With native PHP ZIP/GD (CI), validate the complete signed Apple archive using an ephemeral certificate.
if(class_exists('ZipArchive')&&function_exists('imagecreatetruecolor')){
    define('DECKA_DIR',__DIR__.'/../plugin/');
    function is_wp_error($v){return false;}
    function wp_get_image_editor($path){return new class {private int $size=29;function resize($w,$h,$crop){$this->size=$w;}function save($path,$mime){$im=imagecreatetruecolor($this->size,$this->size);imagepng($im,$path);imagedestroy($im);return ['path'=>$path];}};}
    $csr=openssl_csr_new(['commonName'=>'Decka local test'],$key,['digest_alg'=>'sha256']);$cert=openssl_csr_sign($csr,null,$key,1,['digest_alg'=>'sha256']);openssl_x509_export($cert,$pem);
    Decka_DB::$settings+=['apple_pass_type'=>'pass.test.decka','apple_team_id'=>'TESTTEAM00','apple_certificate'=>$pem,'apple_private_key'=>$private,'apple_wwdr'=>$pem];
    $bytes=Decka_Wallet::apple($doc,(object)['mode'=>'test']);$file=tempnam(sys_get_temp_dir(),'decka-test');file_put_contents($file,$bytes);$zip=new ZipArchive();check($zip->open($file)===true,'Apple signed pass opens as ZIP');$manifest=json_decode($zip->getFromName('manifest.json'),true);foreach($manifest as $name=>$hash)check(sha1($zip->getFromName($name))===$hash,'Apple manifest matches '.$name);check(strlen($zip->getFromName('signature'))>128,'Apple PKCS7 detached signature present');$pass=json_decode($zip->getFromName('pass.json'),true);check($pass['barcodes'][0]['message']===$doc['token'],'Apple preserves package QR');$zip->close();unlink($file);
}
