<?php
/** Real checkout/service with deterministic PayU HTTP fixtures. No live money. */
require __DIR__.'/integration.php';
require DECKA_DIR.'includes/payu.php';
function rest_url($p){return home_url('/wp-json/'.$p);}function wp_parse_url($u,$part){return parse_url($u,$part);}
function get_transient($k){return $GLOBALS['transients'][$k]??false;}function set_transient($k,$v,$ttl){$GLOBALS['transients'][$k]=$v;}
function update_option($k,$v,$autoload=false){$GLOBALS['options'][$k]=$v;}
function is_wp_error($v){return false;}function wp_remote_retrieve_body($r){return $r['body'];}function wp_remote_retrieve_response_code($r){return $r['code'];}
$payments=[];$calls=[];$cancelFail=false;$payOnCancel=false;$badRedirect=false;
function wp_remote_request($url,$args){global $payments,$calls,$cancelFail,$payOnCancel,$badRedirect;$calls[]=[$url,$args];check($args['redirection']===0,'PayU never follows API redirects');
 if(str_contains($url,'oauth/authorize'))return ['code'=>200,'body'=>json_encode(['access_token'=>'fixture-token','expires_in'=>3600])];
 $path=explode('/api/v2_1/',$url)[1];$method=$args['method'];check($args['headers']['Authorization']==='Bearer fixture-token','PayU authenticated request');
 if($path==='orders'&&$method==='POST'){$p=json_decode($args['body'],true);$id='ORDER'.count($payments);$payments[$id]=$p+['orderId'=>$id,'status'=>'PENDING'];return ['code'=>302,'body'=>json_encode(['status'=>['statusCode'=>'SUCCESS'],'orderId'=>$id,'redirectUri'=>$badRedirect?'https://evil.test/':'https://secure.snd.payu.com/pay?order='.$id])];}
 $id=explode('/',$path)[1];if(str_contains($path,'/refunds/'))return ['code'=>200,'body'=>json_encode(['refundId'=>'REF1','status'=>'FINALIZED','amount'=>'2500','currencyCode'=>'PLN'])];
 if($method==='DELETE'){if($payOnCancel)$payments[$id]['status']='COMPLETED';elseif(!$cancelFail)$payments[$id]['status']='CANCELED';return ['code'=>$cancelFail||$payOnCancel?400:200,'body'=>json_encode(['status'=>['statusCode'=>$cancelFail||$payOnCancel?'ERROR':'SUCCESS']])];}
 return ['code'=>200,'body'=>json_encode(['orders'=>[$payments[$id]],'status'=>['statusCode'=>'SUCCESS']])];
}
function notifyPayu($id,$refund=false){global $payments;$p=$payments[$id];$b=$refund?['orderId'=>$id,'extOrderId'=>$p['extOrderId'],'refund'=>['refundId'=>'REF1']]:['order'=>$p];$raw=json_encode($b);return Decka_Payu::webhook('test',$raw,'sender=checkout;signature='.md5($raw.'second').' ;algorithm=MD5');}
$uid=2000;$settings['payment_provider']='payu';foreach(['pos_id'=>'123','client_id'=>'456','client_secret'=>base64_encode('secret'),'second_key'=>base64_encode('second')] as $k=>$v)$settings['payu_test_'.$k]=$v;
$pay=buy(110);$o=Decka_Service::order($pay['order_id']);$pid=substr($o->session_id,5);check(Decka_Service::provider($o)==='payu'&&$o->status==='pending','PayU creates pending checkout');check($payments[$pid]['validityTime']<=600,'PayU reservation capped at ten minutes');check((int)$wpdb->get_var('SELECT COUNT(*) FROM wp_dect_tickets WHERE order_id='.$o->id)===0,'PayU pending never issues tickets');
$raw=json_encode(['order'=>$payments[$pid]]);rejects(fn()=>Decka_Payu::webhook('test',$raw,'signature=wrong;algorithm=MD5'),'invalid signature rejected');check(!Decka_Payu::signature($raw.' ', 'signature='.md5($raw.'second').';algorithm=MD5','second'),'signature binds exact raw body');
foreach(['totalAmount'=>'1','currencyCode'=>'EUR','merchantPosId'=>'999','extOrderId'=>'wrong','orderId'=>'OTHER'] as $k=>$v){$bad=$payments[$pid];$bad[$k]=$v;rejects(fn()=>Decka_Payu::normalize($o,$bad),'mismatched '.$k.' rejected');}
$settings['payment_provider']='stripe';$payments[$pid]['status']='COMPLETED';notifyPayu($pid);notifyPayu($pid);check(Decka_Service::order($o->id)->status==='paid','existing PayU order settles after switching operator');check((int)$wpdb->get_var('SELECT COUNT(*) FROM wp_dect_tickets WHERE order_id='.$o->id)===1,'duplicate PayU webhook issues one ticket');rejects(fn()=>Decka_Service::settle(Decka_Payu::normalize($o,$payments[$pid]),'test','stripe'),'Stripe cannot settle PayU order');
notifyPayu($pid,true);check(Decka_Service::order($o->id)->status==='refunded','top-level PayU refund notification revokes order');check($wpdb->get_var('SELECT status FROM wp_dect_tickets WHERE order_id='.$o->id)==='revoked','refund revokes issued ticket');notifyPayu($pid);check(Decka_Service::order($o->id)->status==='refunded','late completed cannot undo refund');
$settings['payment_provider']='payu';$expire=buy(111);Decka_DB::update('orders',['created_at'=>gmdate('Y-m-d H:i:s',time()-601)],['id'=>$expire['order_id']]);$o=Decka_Service::order($expire['order_id']);$cancelFail=true;rejects(fn()=>Decka_Service::refresh_payment($o),'uncertain cancellation keeps reservation');check((int)$wpdb->get_var('SELECT COUNT(*) FROM wp_dect_inventory WHERE order_id='.$o->id)===1,'failed cancellation retains seat');$cancelFail=false;Decka_Service::refresh_payment($o);check(Decka_Service::order($o->id)->status==='expired','confirmed cancellation expires order');check((int)$wpdb->get_var('SELECT COUNT(*) FROM wp_dect_inventory WHERE order_id='.$o->id)===0,'confirmed cancellation releases seat');
$race=buy(112);$payOnCancel=true;Decka_Payu::refresh(Decka_Service::order($race['order_id']),true);$payOnCancel=false;check(Decka_Service::order($race['order_id'])->status==='paid','payment wins cancellation race');
$early=buy(113);$id=substr(Decka_Service::order($early['order_id'])->session_id,5);$payments[$id]['status']='COMPLETED';notifyPayu($id,true);check((int)$wpdb->get_var('SELECT COUNT(*) FROM wp_dect_tickets WHERE order_id='.$early['order_id'])===0,'refund before completed notification never issues ticket');
$badRedirect=true;rejects(fn()=>buy(114),'foreign checkout redirect rejected');check(Decka_Payu::host('live')==='https://secure.payu.com','live uses separate API host');rejects(fn()=>Decka_Payu::host('other'),'invalid environment rejected');
echo "TOTAL $checks integration + PayU fixture checks\n";
