import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const req=createRequire(import.meta.url);
const pngRequire=createRequire(req.resolve('qrcode'));
const {PNG}=pngRequire('pngjs');
const uiRequire=createRequire(new URL('../frontend/package.json',import.meta.url));
const zxRequire=createRequire(uiRequire.resolve('@zxing/browser'));
const {RGBLuminanceSource,HybridBinarizer,BinaryBitmap,QRCodeReader}=zxRequire('@zxing/library');
const png=PNG.sync.read(fs.readFileSync('../../outputs/decka-bilety/bilet-podglad.png'));
const gray=new Uint8ClampedArray(png.width*png.height);
for(let i=0;i<gray.length;i++)gray[i]=(png.data[i*4]+2*png.data[i*4+1]+png.data[i*4+2])/4;
const text=new QRCodeReader().decode(new BinaryBitmap(new HybridBinarizer(new RGBLuminanceSource(gray,png.width,png.height)))).getText();
assert.equal(text,fs.readFileSync('tests/expected-qr.txt','utf8'));
console.log('PASS: QR decoded from rendered A4 PDF matches the ticket token exactly.');
