/** UI regression checks against the built static admin, using isolated API fixtures. */
import {chromium,launchOptions} from './browser.mjs';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve('frontend/out');
const browser=await chromium.launch(launchOptions);
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const stamp=new Date().toISOString();
const database={namespace:'dect',version:'0.3.6',expected:'0.3.6',audit:{ok:true,checked_at:stamp,issues:[]},inventory:{source_prefix:'wp_decka_',target_prefix:'wp_dect_',tables:[{name:'orders',source:{exists:true,rows:12,engine:'InnoDB'},target:{exists:true,rows:12,engine:'InnoDB'}}]}};
const boot={version:'0.3.6',mode:'test',events:[],alerts:[],offers:[],promos:[],seats:{seats:[]},settings:{database,normal:2500,reduced:1500,max_per_fan:10,mode:'test',registration:1,league_url:'https://example.test/team',team_id:7625,ticket_color:'#19569d',test_secret_set:true,test_webhook_set:true,https:true,wallet_zip:true,test_webhook_url:'https://example.test/test',live_webhook_url:'https://example.test/live'},permissions:{updates:true,users:true},links:{plugins:'#'},updater:{status:'current'}};
boot.seats=JSON.parse(fs.readFileSync('plugin/data/seats.json','utf8'));
boot.events=[{id:1,opponent:'Test raportu',image_url:'/match.svg',starts_at:'2030-10-10 16:00:00',stats:{normal:100,reduced:50,entered:80,paid_entered:70,available:180,revenue:325000}}];
let saved;
await page.route('http://decka-ui.test/**',async route=>{const url=new URL(route.request().url());
 if(url.pathname==='/api/admin/media')return route.fulfill({json:{id:999,url:'/match.svg'}});
 if(url.pathname==='/api/admin/inventory')return route.fulfill({json:[]});
 if(url.pathname==='/api/admin/payu/check')return route.fulfill({json:{ok:true,message:'PayU fixture connected'}});
 if(url.pathname==='/api/admin/gate/search')return route.fulfill({json:[{id:2,name:'Tomasz Test',email:'tom@example.test',enabled:false}]});
 if(url.pathname==='/api/admin/gate')return route.fulfill({json:{scans:[],users:[{id:1,name:'Administrator Test',email:'admin@example.test',administrator:true}]}});
 if(url.pathname==='/match.svg')return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1008"><rect width="1920" height="1008" fill="#19569d"/></svg>'});
 if(url.pathname==='/api/admin/orders')return route.fulfill({json:{rows:[{id:123,email:'buyer@example.test',status:'paid',total:2500,created_at:'2030-10-01 10:00:00',positions_count:1}],page:1,total:1}});
 if(url.pathname==='/api/admin/orders/123')return route.fulfill({json:{id:123,email:'buyer@example.test',status:'paid',total:2500,discount:0,items:[{id:1,event_id:1,opponent:'Test raportu',starts_at:'2030-10-10 16:00:00',venue:'Hala Pelplin',seat_id:'66',seat:{sector:'B',row:1,number:66},kind:'normal',amount:2500,ticket_number:'DK-000000123',ticket_status:'valid'}]}});
 if(url.pathname==='/api/admin/bootstrap')return route.fulfill({json:boot});
 if(url.pathname==='/api/admin/action'){
  const p=route.request().postDataJSON();
  if(p.operation==='settings'){saved=p;boot.settings.normal=p.normal;return route.fulfill({json:{message:'Zapisano zmiany.'}});}
  if(p.operation==='database_inspect'){database.audit.checked_at=new Date().toISOString();return route.fulfill({json:{message:'Sprawdzono stan bazy.'}});}
  database.status={state:'failed',time:stamp,step:'copy',table:'orders',message:'Migracja nie została zakończona.',diagnostic:{reason:'duplicate',index:'request_once',reference:'DB-ORDERS-UI',time:stamp,table:'orders',operation:'query'}};
  return route.fulfill({status:400,json:{message:'Migracja nie została zakończona.'}});
 }
 const file=path.join(root,url.pathname==='/admin/'?'admin/index.html':decodeURIComponent(url.pathname));
 if(!fs.existsSync(file)||fs.statSync(file).isDirectory())return route.fulfill({status:404,body:''});
 let body=fs.readFileSync(file);const type=({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.woff2':'font/woff2'}[path.extname(file)]||'application/octet-stream');
 if(type==='text/html')body=Buffer.from(body.toString().replace('<head>','<head><base href="http://decka-ui.test/"/><script>window.DECKA={api:"http://decka-ui.test/api/",nonce:"test",adminScreen:"settings"}</script>'));
 return route.fulfill({body,contentType:type});
});
const tab=name=>page.getByRole('navigation',{name:'Kategorie ustawień'}).getByRole('button',{name:new RegExp('^'+name+'(?: Wymaga uwagi)?$')});
await page.goto('http://decka-ui.test/admin/');await page.getByRole('heading',{name:'Zasady sprzedaży'}).waitFor();
assert.equal(await page.getByLabel('Filtr meczu').count(),0,'irrelevant event filter hidden');
await tab('Płatności').click();assert.equal(await page.locator('input[name=payu_test_pos_id]').isVisible(),false);await page.getByText('2. PayU',{exact:true}).click();await page.getByRole('button',{name:'Sprawdź połączenie z PayU',exact:true}).click();await page.getByText('PayU fixture connected',{exact:true}).waitFor();await page.locator('select[name=payment_provider]').selectOption('payu');await page.locator('input[name=payu_test_pos_id]').fill('123');await page.locator('input[name=payu_test_client_secret]').fill('fixture-payu-secret');await page.screenshot({path:'tests/artifacts/payu-settings-desktop.png',fullPage:true});await tab('Sprzedaż').click();await tab('Bilety i e-mail').click();await page.getByLabel('Plik z logotypami sponsorów').setInputFiles('frontend/public/logo.png');await page.getByAltText('Pasek sponsorów do biletu').waitFor();await tab('Sprzedaż').click();await page.getByLabel('Bilet normalny (zł)',{exact:true}).fill('30');
await tab('Płatności').click();await page.locator('input[name="test_secret"]').fill('sk_test_fixture');
await tab('System').click();await page.getByRole('button',{name:'Sprawdź stan bazy',exact:true}).click();await page.getByText('Sprawdzono stan bazy.',{exact:true}).waitFor();
await tab('Sprzedaż').click();assert.equal(await page.getByLabel('Bilet normalny (zł)',{exact:true}).inputValue(),'30','draft survives tab and diagnostic refresh');
await tab('Płatności').click();assert.equal(await page.locator('input[name="test_secret"]').inputValue(),'sk_test_fixture');
await page.getByRole('button',{name:'Zapisz zmiany',exact:true}).click();await page.getByText('Zapisano zmiany.',{exact:true}).waitFor();assert.equal(saved.payment_provider,'payu');assert.equal(saved.payu_test_pos_id,'123');assert.equal(saved.payu_test_client_secret,'fixture-payu-secret');assert.equal(saved.sponsor_image_id,'999');assert.equal(saved.normal,3000);assert.equal(saved.reduced,1500);assert.equal(saved.registration,true);assert.equal(saved.test_secret,'sk_test_fixture');assert.equal(saved.team_id,'7625');
assert.equal(await tab('Płatności').getAttribute('aria-current'),'page','saving preserves active category');
await tab('Portfele').click();assert.equal(await page.getByLabel('Pass Type ID',{exact:true}).isVisible(),false);await page.getByRole('switch',{name:'Włącz Apple Wallet'}).check();await page.getByLabel('Pass Type ID',{exact:true}).fill('pass.test');await page.getByRole('switch',{name:'Włącz Apple Wallet'}).uncheck();assert.equal(await page.getByLabel('Pass Type ID',{exact:true}).isVisible(),false);await page.getByRole('switch',{name:'Włącz Apple Wallet'}).check();assert.equal(await page.getByLabel('Pass Type ID',{exact:true}).inputValue(),'pass.test');await page.getByRole('switch',{name:'Włącz Google Wallet'}).check();assert.equal(await page.getByLabel('Issuer ID',{exact:true}).isVisible(),true);
await tab('Liga').click();await page.getByLabel('Adres terminarza ligi').fill('invalid-url');await tab('Sprzedaż').click();await page.getByRole('button',{name:'Zapisz zmiany',exact:true}).click();await page.getByLabel('Adres terminarza ligi').waitFor({state:'visible'});await page.getByLabel('Adres terminarza ligi').fill('https://example.test/team');
database.namespace='pending';await tab('System').click();await page.getByRole('button',{name:'Sprawdź stan bazy',exact:true}).click();await page.getByRole('button',{name:'Ponów migrację',exact:true}).waitFor();
await page.getByRole('button',{name:'Ponów migrację',exact:true}).click();await page.getByRole('alert').getByText('Migracja nie została zakończona.',{exact:true}).waitFor();await page.getByText('Powtórzona wartość klucza unikatowego · request_once',{exact:true}).waitFor();
assert.equal(await page.getByRole('heading',{name:'Zapisany błąd'}).isVisible(),false,'technical history collapsed');
const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Pobierz raport',exact:true}).click();const download=await downloadPromise;const content=fs.readFileSync(await download.path(),'utf8');assert.equal(JSON.parse(content).status.diagnostic.index,'request_once');assert.ok(!content.includes('sk_test_fixture'));
fs.mkdirSync('tests/artifacts',{recursive:true});await page.screenshot({path:'tests/artifacts/settings-system-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
for(const name of ['Sprzedaż','Płatności','Konta kibiców','Bilety i e-mail','Portfele','Liga','System']){await tab(name).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no mobile overflow: '+name);}
await page.screenshot({path:'tests/artifacts/settings-system-mobile.png',fullPage:true});assert.deepEqual(errors,[]);
await page.locator('.da-nav').getByRole('button',{name:'Raporty',exact:true}).click();await page.getByRole('img',{name:'Zapełnienie ze sprzedaży: 44.1%, 150 z 340',exact:true}).waitFor();await page.getByRole('img',{name:'Wejścia z opłaconych biletów: 46.7%, 70 z 150',exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'tests/artifacts/reports-mobile.png',fullPage:true});
await page.locator('.da-nav').getByRole('button',{name:'Wejścia i bileterzy',exact:true}).click();await page.getByRole('button',{name:'Nadaj dostęp',exact:true}).click();await page.getByLabel('Znajdź kibica').fill('tom');await page.getByRole('button',{name:/Tomasz Test/}).click();assert.equal(await page.locator('input[name="email"]').inputValue(),'tom@example.test');assert.equal(await page.getByRole('button',{name:'Zapisz i zatwierdź'}).isEnabled(),true);assert.deepEqual(errors,[]);
await page.getByRole('button',{name:'Anuluj',exact:true}).click();await page.getByRole('button',{name:'Usuń biletera',exact:true}).click();await page.getByText('Usunąć admin@example.test z zespołu bileterów?',{exact:false}).waitFor();await page.getByRole('button',{name:'Anuluj',exact:true}).click();
await page.locator('.da-nav').getByRole('button',{name:'Zamówienia',exact:true}).click();assert.equal(await page.locator('.da-topbar select').count(),0);await page.locator('.da-content').getByLabel('Filtr meczu').waitFor();await page.getByRole('button',{name:'Szczegóły',exact:true}).click();await page.getByText('DK-000000123',{exact:true}).waitFor();await page.getByRole('heading',{name:'Decka Pelplin — Test raportu',exact:true}).waitFor();assert.equal(await page.locator('.da-seat-chips').innerText(),'Sektor B\nRząd 1\nMiejsce 66');await page.screenshot({path:'tests/artifacts/order-detail-mobile.png',fullPage:true});await page.getByRole('button',{name:'Zamknij',exact:true}).click();
await page.locator('.da-nav').getByRole('button',{name:'Mecze',exact:true}).click();await page.locator('.da-event-image').waitFor();assert.equal(await page.locator('.da-event-image').evaluate(el=>getComputedStyle(el).objectFit),'contain');assert.deepEqual(errors,[]);
await page.locator('.da-nav').getByRole('button',{name:'Plan hali',exact:true}).click();await page.getByRole('button',{name:/Sektor B/}).click();const seat=page.getByRole('button',{name:'66 wolne',exact:true});await seat.waitFor();assert.equal(await seat.locator('circle').getAttribute('fill'),'#b8d5f4');await seat.click();assert.equal(await seat.locator('circle').getAttribute('fill'),'#19569d');assert.equal(await seat.evaluate(e=>getComputedStyle(e).outlineStyle),'none');await page.screenshot({path:'tests/artifacts/hall-selected-mobile.png',fullPage:true});
console.log('PASS settings: full order detail, in-content match filter, admin removal control, uncropped event image, dynamic gate search, wallet switches retain values, reports correctly calculate occupancy and paid entries, categories, draft retention, full save payload, invalid-field navigation, migration failure refresh, safe report download, mobile, no JS errors');await browser.close();
