import {chromium,launchOptions} from './browser.mjs';
import assert from 'node:assert/strict';
const browser=await chromium.launch(launchOptions);
const page=await browser.newPage({viewport:{width:1440,height:1300},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8765/');
await page.locator('.product-tile').first().click();
await page.getByRole('heading',{name:'Plan hali'}).waitFor();
await page.screenshot({path:'../../outputs/decka-bilety/podglad-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Powiększ sektor C'}).click();
assert.equal(await page.locator('button.seat').count(),130);
await page.getByRole('button',{name:'Sektor C, rząd 1, miejsce 180',exact:true}).click();
await page.getByLabel('Rodzaj biletu miejsce 180').selectOption('reduced');
assert.equal(await page.locator('.total strong').textContent(),'15,00 zł');
await page.getByRole('button',{name:'Dalej — dane kupującego'}).click();
await page.getByRole('alertdialog').filter({hasText:'To podgląd interfejsu'}).waitFor();
await page.getByRole('button',{name:/Rozumiem/}).click();
await page.getByRole('button',{name:'Cała hala'}).click();
assert.equal(await page.locator('svg circle.chosen').count(),1);
await page.getByRole('button',{name:'Powiększ sektor A'}).click();
assert.equal(await page.locator('button.seat').count(),65);
await page.getByRole('button',{name:'Cała hala'}).click();
await page.getByRole('button',{name:'Powiększ sektor B'}).click();
assert.equal(await page.locator('button.seat').count(),105);
await page.getByRole('button',{name:'Cała hala'}).click();
await page.getByRole('button',{name:'Powiększ sektor D'}).click();
assert.equal(await page.locator('button.seat').count(),105);
await page.getByRole('button',{name:'Cała hala'}).click();
await page.getByRole('button',{name:'Powiększ sektor E'}).click();
assert.equal(await page.locator('button.seat').count(),65);
await page.getByRole('button',{name:'Cała hala'}).click();
await page.getByRole('button',{name:/Wszystkie mecze i mini-karnety/}).click();
await page.locator('.package-tile').click();
assert.equal(await page.locator('.seat-line').count(),0);
await page.getByRole('button',{name:'Powiększ sektor B'}).click();
await page.getByRole('button',{name:'Sektor B, rząd 1, miejsce 66',exact:true}).click();
assert.equal(await page.locator('.total strong').textContent(),'65,00 zł');
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'../../outputs/decka-bilety/podglad-mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
assert.deepEqual(errors,[]);
console.log('PASS UI: 470 seats in sectors A-E, sector zoom, selection, reduced price, package price, demo guard, mobile overflow, no JS errors');
await browser.close();
