'use client';
import {useEffect,useRef,useState,useCallback} from 'react';
import {ArrowLeft,ArrowRight,CalendarDays,Check,ChevronDown,Clock3,Download,Expand,MapPin,Minus,ScanLine,ShieldCheck,Ticket,UserRound,X,Camera,LogOut} from 'lucide-react';
type Seat={id:string;number:number;sector:string;row:number;x:number;y:number};
type Game={id:number;opponent:string;starts_at:string|null;date_label?:string;venue:string;sale_open:number;normal_price?:number;reduced_price?:number;image_url?:string};
type Offer={id:number;name:string;event_ids:string;normal_price:number;reduced_price:number};
type Config={api:string;nonce:string;authNonce:string;user:null|{name:string;email:string;gate:boolean;admin:boolean};view?:string;order?:number;resetUrl?:string;privacyUrl?:string;termsUrl?:string;googleLogin?:string};
type Catalog={mode:string;normal:number;reduced:number;seats:{seats:Seat[];cameras:{x:number;y:number}[];sectors:{id:string;count:number}[]};events:Game[];offers:Offer[];registration:boolean;max_per_fan?:number};
type Order={id:number;status:string;mode:string;total:number;download:string|null;checkout_url?:string;wallet?:{label:string;url:string}[];items:{seat_id:string;kind:string;opponent:string;starts_at:string}[]};
declare global {interface Window {DECKA?:Config}}
const requestId=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
const money=(n:number)=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',maximumFractionDigits:2}).format(n/100);
const date=(s:string|null,opts:Intl.DateTimeFormatOptions={day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})=>s?new Intl.DateTimeFormat('pl-PL',{...opts,timeZone:'Europe/Warsaw'}).format(new Date(s.replace(' ','T')+'Z')):'Termin do potwierdzenia';
const statusNames:Record<string,string>={creating:'Przygotowanie płatności',pending:'Oczekuje na płatność',paid:'Opłacone',free:'Bilet bezpłatny',voucher:'VOUCHER',expired:'Płatność wygasła',refunded:'Unieważnione / zwrot'};
export default function Home(){
 const [config,setConfig]=useState<Config|null>(null),[catalog,setCatalog]=useState<Catalog|null>(null),[demo,setDemo]=useState(false),[tab,setTab]=useState('shop');
 const [eventId,setEventId]=useState(0),[offerId,setOfferId]=useState(0),[sector,setSector]=useState<string|null>(null),[selected,setSelected]=useState<Record<string,string>>({}),[occupied,setOccupied]=useState<Record<string,string>>({});
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(false),[register,setRegister]=useState(false),[promo,setPromo]=useState(''),[orders,setOrders]=useState<Order[]>([]),[fresh,setFresh]=useState(false);
 const [productChosen,setProductChosen]=useState(false),[packageAck,setPackageAck]=useState(false);
 const requestKey=useRef('');const offer=catalog?.offers.find(o=>Number(o.id)===offerId);const game=catalog?.events.find(e=>Number(e.id)===eventId);const eventIds=offer?JSON.parse(offer.event_ids).map(Number):eventId?[eventId]:[];const idsKey=eventIds.join(',');
 const api=useCallback(async(path:string,body?:unknown)=>{if(!config)throw Error('Trwa ładowanie.');const r=await fetch(config.api+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-WP-Nonce':config.nonce},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.message||'Nie udało się wykonać operacji.');return data;},[config]);
 useEffect(()=>{const send=()=>{if(window.parent!==window)window.parent.postMessage({type:'decka-height',height:document.body.scrollHeight},location.origin)};const observer=typeof ResizeObserver!=='undefined'?new ResizeObserver(send):null;observer?.observe(document.body);window.addEventListener('resize',send);send();return()=>{observer?.disconnect();window.removeEventListener('resize',send)};},[]);
 useEffect(()=>{async function init(){try{const cfg=window.DECKA;if(cfg){setConfig(cfg);setTab(cfg.view==='gate'?'gate':cfg.order?'account':'shop');const r=await fetch(cfg.api+'catalog',{cache:'no-store'});if(!r.ok)throw Error('Nie można pobrać oferty.');const c=await r.json();setCatalog(c);try{const saved=sessionStorage.getItem('decka-cart');if(saved){const cart=JSON.parse(saved);sessionStorage.removeItem('decka-cart');if(Date.now()-cart.at<3600000){setOfferId(Number(cart.offerId)||0);setSelected(cart.selected||{});setProductChosen(true);setPackageAck(!!cart.packageAck);setEventId(Number(cart.eventId)||0);return;}}}catch{}setEventId(Number(c.events.find((e:Game)=>Number(e.sale_open))?.id||c.events[0]?.id||0));}else{setDemo(true);const seats=await fetch('./seats.json').then(r=>r.json());setCatalog({mode:'demo',normal:2500,reduced:1500,seats,registration:true,events:[{id:1,opponent:'Drużyna gości',starts_at:'2026-10-10 16:00:00',venue:'Hala ZKiW nr 1 · Pelplin',sale_open:1}],offers:[{id:1,name:'Pakiet 3 meczów — przykład',event_ids:'[1,2,3]',normal_price:6500,reduced_price:3900}]});setEventId(1);setFresh(true);}}catch(e){setError((e as Error).message);}}init();},[]);
 useEffect(()=>{if(!idsKey||!config)return;let stopped=false;setFresh(false);const refresh=async()=>{try{const data=await api('availability?events='+idsKey);if(stopped)return;const states:Record<string,string>={};for(const s of data.seats){if(states[s.seat_id]!=='paid')states[s.seat_id]=s.state;}setOccupied(states);setFresh(true);setSelected(old=>Object.fromEntries(Object.entries(old).filter(([id])=>!states[id])));}catch{if(!stopped)setFresh(false);}};refresh();const t=setInterval(refresh,8000);return()=>{stopped=true;clearInterval(t);}},[idsKey,config,api]);
 useEffect(()=>{if(tab!=='account'||!config?.user)return;const load=()=>api('orders').then(setOrders).catch(e=>setError(e.message));load();const timer=setInterval(load,5000);return()=>clearInterval(timer);},[tab,config,api]);
 const changeProduct=(id:number,isOffer=false)=>{setProductChosen(true);setPackageAck(false);setOfferId(isOffer?id:0);if(!isOffer)setEventId(id);setSelected({});setSector(null);requestKey.current='';setNotice('');};
 const toggle=(s:Seat)=>{if(occupied[s.id]||!fresh||(!offer&&!Number(game?.sale_open)))return;setError('');requestKey.current='';setSelected(old=>{const n={...old};if(n[s.id])delete n[s.id];else if(Object.keys(n).length<Math.min(10,catalog?.max_per_fan||10))n[s.id]='normal';else setError('Osiągnięto limit miejsc w zamówieniu.');return n;});};
 const items=catalog?.seats.seats.filter(s=>selected[s.id])||[];const price=(kind:string)=>Number(offer?(kind==='normal'?offer.normal_price:offer.reduced_price):(kind==='normal'?(game?.normal_price??catalog?.normal):(game?.reduced_price??catalog?.reduced)))||0;const total=items.reduce((n,s)=>n+price(selected[s.id]),0);
 async function checkout(){setError('');if(demo){setNotice('To podgląd interfejsu. Płatności, konta i bilety uruchamiają się po instalacji w WordPressie.');return;}if(!config?.user){setModal(true);return;}if(!fresh){setError('Nie można potwierdzić dostępności miejsc. Spróbuj ponownie.');return;}setBusy(true);try{requestKey.current ||= requestId();const res=await api('checkout',{request_key:requestKey.current,event_id:eventId,offer_id:offerId,seats:items.map(s=>({id:s.id,kind:selected[s.id]})),promo,package_ack:packageAck});if(res.url)(window.top||window).location.assign(res.url);else{setTab('account');setSelected({});}}catch(e){setError((e as Error).message);setTab('account');}finally{setBusy(false);}}
 async function auth(ev:React.FormEvent<HTMLFormElement>){ev.preventDefault();setBusy(true);setError('');try{const f=new FormData(ev.currentTarget);const cfg=await api(register?'register':'login',{email:f.get('email'),password:f.get('password'),name:f.get('name'),auth_nonce:config?.authNonce});setConfig({...config,...cfg});setModal(false);setNotice(tab==='gate'?'':'Jesteś zalogowany. Możesz przejść do płatności.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function googleLogin(){if(!config?.googleLogin)return;try{sessionStorage.setItem('decka-cart',JSON.stringify({eventId,offerId,selected,packageAck,at:Date.now()}));}catch{}(window.top||window).location.assign(config.googleLogin);}
 return <div className={"shell "+(tab==='gate'?'gate-shell':'')}>
  <header><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('shop');setProductChosen(false)}}><img src="./logo.png" alt="Herb Decka Pelplin"/><span>DECKA <b>PELPLIN</b><small>OFICJALNY SYSTEM BILETOWY</small></span></a><nav><button className={tab==='shop'?'active':''} onClick={()=>setTab('shop')}>Bilety i karnety</button><button className={tab==='account'?'active':''} onClick={()=>{setTab('account');if(!demo&&!config?.user)setModal(true)}}><UserRound size={17}/> Moje bilety</button></nav></header>
  {demo?<div className="environment">PODGLĄD PROJEKTU <span>Przykładowy mecz i oferta. Miejsca pochodzą z Twojego Excela.</span></div>:catalog?.mode==='test'?<div className="environment">ŚRODOWISKO TESTOWE <span>Płatności i bilety testowe.</span></div>:null}
  {error&&<div className="alert error" role="alert">{error}<button aria-label="Zamknij komunikat" onClick={()=>setError('')}><X size={18}/></button></div>}
  {notice&&<div className="alert" role="status">{notice}<button aria-label="Zamknij komunikat" onClick={()=>setNotice('')}><X size={18}/></button></div>}
  {!catalog?<div className="empty">{error?'Nie udało się załadować sprzedaży. Odśwież stronę.':'Ładujemy dostępne miejsca…'}</div>:tab==='shop'?<>
   <section className="hero"><div><span className="eyebrow">WIDZIMY SIĘ W HALI</span><h1>Twoje miejsce.<br/><span>Nasza drużyna.</span></h1><p>Wybierz mecz, znajdź swoje miejsce<br className="desktop"/> i kibicuj Decce z trybun.</p></div><div className="hero-ticket"><Ticket size={38}/><span>BLISKO PARKIETU.<br/>BLISKO EMOCJI.</span><div className="price-tags">{productChosen?<><span>Normalny <b>{money(price('normal'))}</b></span><span>Ulgowy <b>{money(price('reduced'))}</b></span></>:<span>Mecze i mini-karnety<br/>Wybierz swoją ofertę poniżej</span>}</div></div></section>
   <div className="steps"><span className="current"><b>1</b> Mecz i miejsca</span><i/><span className={config?.user?'done':''}><b>{config?.user?<Check size={13}/>:2}</b> Twoje konto</span><i/><span><b>3</b> Płatność i bilety</span></div>
   {!productChosen?<section className="product-tiles" aria-label="Mecze i mini-karnety">{catalog.events.filter(e=>Number(e.sale_open)).map(e=><button className="product-tile" key={'event-'+e.id} onClick={()=>changeProduct(Number(e.id))}>{e.image_url?<img src={e.image_url} alt=""/>:<img className="tile-logo" src="./logo.png" alt=""/>}<span className="eyebrow">BILETY NA MECZ</span><h2>Decka Pelplin — {e.opponent}</h2><strong><CalendarDays size={20}/>{date(e.starts_at)}</strong><p><MapPin size={19}/>{e.venue}</p><span>Normalny {money(e.normal_price??catalog.normal)} · ulgowy {money(e.reduced_price??catalog.reduced)}</span><b>Wybierz miejsca →</b></button>)}{catalog.offers.map(o=><button className="product-tile package-tile" key={'offer-'+o.id} onClick={()=>changeProduct(Number(o.id),true)}><LayersIcon/><span className="eyebrow">MINI-KARNET</span><h2>{o.name}</h2><p>{JSON.parse(o.event_ids).length} meczów · jedno miejsce</p><strong>Normalny {money(o.normal_price)} · ulgowy {money(o.reduced_price)}</strong><b>Zobacz mecze i wybierz miejsca →</b></button>)}{!catalog.events.some(e=>Number(e.sale_open))&&!catalog.offers.length&&<p className="empty">Sprzedaż kolejnych meczów wkrótce.</p>}</section>:<><button className="back" onClick={()=>{setProductChosen(false);setSelected({})}}><ArrowLeft size={18}/> Wszystkie mecze i mini-karnety</button><section className="selected-product"><h2>{offer?offer.name:'Decka Pelplin — '+game?.opponent}</h2>{!offer&&<><strong><CalendarDays/> {date(game?.starts_at||null)}</strong><p><MapPin/> {game?.venue}</p></>}{offer&&<><ul>{eventIds.map((id:number)=>{const match=catalog.events.find(e=>Number(e.id)===id);return <li key={id}><b>Decka Pelplin — {match?.opponent||'Mecz #'+id}</b><span>{date(match?.starts_at||null)} · {match?.venue}</span></li>})}</ul><label className="package-ack"><input type="checkbox" checked={packageAck} onChange={e=>setPackageAck(e.target.checked)}/>Przyjmuję do wiadomości, że terminy meczów mogą się zmienić. Zakup obejmuje wymienione spotkania, z zachowaniem ustawowych praw konsumenta.</label></>}</section>
   <div className="purchase-grid"><section className="map-card"><div className="section-head"><div><span className="eyebrow">WYBIERZ SWOJE MIEJSCA</span><h2>{sector?'Sektor '+sector:'Plan hali'}</h2></div>{sector?<button className="back" onClick={()=>setSector(null)}><ArrowLeft size={16}/> Cała hala</button>:<span className="hint"><Expand size={16}/> Kliknij sektor, aby przybliżyć</span>}</div>
    <SeatMap catalog={catalog} normal={price('normal')} reduced={price('reduced')} sector={sector} selected={selected} occupied={occupied} onSector={setSector} onToggle={toggle} disabled={!fresh||(!offer&&!Number(game?.sale_open))}/>
    <div className="legend"><span><i className="available"/>Wolne</span><span><i className="chosen"/>Twój wybór</span><span><i className="paid"/>Zajęte</span></div>
    <div className="map-foot"><ShieldCheck size={16}/>{fresh?'Dostępność miejsc jest aktualizowana na bieżąco.':'Sprawdzamy dostępność — wybór chwilowo wstrzymany.'}</div>
   </section><aside className="basket"><span className="eyebrow">TWÓJ WYBÓR</span><h2>{items.length?`${items.length} ${items.length===1?'miejsce':'miejsca'}`:'Wybierz miejsca'}</h2>{items.length?<div className="seat-list">{items.map(s=><div className="seat-line" key={s.id}><div className="seat-number">{s.number}</div><div><b>Sektor {s.sector} <span>· Rząd {s.row}</span></b><select aria-label={'Rodzaj biletu miejsce '+s.number} value={selected[s.id]} onChange={e=>{requestKey.current='';setSelected({...selected,[s.id]:e.target.value})}}><option value="normal">Normalny · {money(price('normal'))}</option><option value="reduced">Ulgowy · {money(price('reduced'))}</option></select></div><button aria-label={'Usuń miejsce '+s.number} onClick={()=>toggle(s)}><X size={15}/></button></div>)}</div>:<div className="basket-empty"><Ticket size={38} strokeWidth={1.2}/><p>Kliknij sektor na mapie,<br/>a następnie wolne miejsca.</p></div>}
    <label className="promo">Masz kod rabatowy?<input value={promo} onChange={e=>{setPromo(e.target.value.toUpperCase());requestKey.current=''}} placeholder="Wpisz kod"/></label><div className="total"><span>{promo?'Razem przed rabatem':'Razem'}</span><strong>{money(total)}</strong></div>{promo&&<small className="muted">Rabat zostanie sprawdzony i naliczony przed płatnością w Stripe.</small>}
    <button className="primary" disabled={!items.length||busy||!fresh||!!offer&&!packageAck} onClick={checkout}>{busy?'Przygotowujemy zamówienie…':config?.user?'Przejdź do płatności':'Dalej — Twoje konto'}<ArrowRight size={18}/></button><p className="secure"><ShieldCheck size={15}/> Bezpieczna płatność przez Stripe</p><div className="payment-brands"><b>BLIK</b><span>VISA</span><span>Mastercard</span></div><p className="fine">Bilety PDF z kodem QR otrzymasz e-mailem po potwierdzeniu płatności. {config?.termsUrl&&<a href={config.termsUrl} target="_blank" rel="noreferrer">Regulamin sprzedaży</a>}</p>
   </aside></div></>}
   <div className="benefits"><div><Ticket/><span><b>Bilet zawsze pod ręką</b><small>Na e-mailu i na Twoim koncie.</small></span></div><div><ScanLine/><span><b>Szybkie wejście do hali</b><small>Pokaż kod QR przy wejściu.</small></span></div><div><MapPin/><span><b>Dokładnie Twoje miejsce</b><small>Wybierasz sektor, rząd i numer.</small></span></div></div>
  </>:tab==='account'?<section className="account"><span className="eyebrow">KONTO KIBICA</span><h1>Moje bilety</h1>{config?.user?<><p>{config.user.email} {config.googleLogin&&<button onClick={googleLogin}>Połącz konto Google</button>} <button className="text-button" onClick={async()=>{await api('logout',{});window.location.reload()}}><LogOut size={15}/> Wyloguj</button></p>{orders.length===0?<div className="empty">Nie masz jeszcze zamówień. <button onClick={()=>setTab('shop')}>Wybierz mecz</button></div>:orders.map(o=><article className="order" key={o.id}><div><small>ZAMÓWIENIE #{o.id} {o.mode==='test'?'· TEST':''}</small><h3>{statusNames[o.status]||o.status}</h3><p>{o.items.map(i=>`${i.opponent} · miejsce ${i.seat_id}`).join(' / ')}</p><b>{money(Number(o.total))}</b></div><div className="order-actions">{o.download&&<a className="primary" href={o.download}><Download size={18}/> Pobierz bilety PDF</a>}{o.wallet?.map(w=><a key={w.url} href={w.url} target="_top">Dodaj do {w.label}</a>)}{o.status==='pending'&&<><a className="primary" href={o.checkout_url} target="_top">Dokończ płatność</a><button onClick={async()=>{try{setBusy(true);await api('orders/'+o.id+'/cancel',{});setOrders(await api('orders'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}} disabled={busy}>Anuluj i zwolnij miejsca</button></>}{o.status==='creating'&&<small>Sprawdzamy połączenie ze Stripe.<br/>Nie twórz kolejnego zamówienia.</small>}</div></article>)}</>:<div className="empty"><UserRound size={35}/><p>Zaloguj się, aby zobaczyć i pobrać bilety.</p><button className="primary" onClick={()=>demo?setNotice('Logowanie będzie dostępne po instalacji w WordPressie.'):setModal(true)}>Zaloguj się</button></div>}</section>:<Gate config={config} api={api} onLogin={()=>setModal(true)}/>}
  <footer><span>DECKA PELPLIN <small>#KoszykarskiPelplin</small></span><span>{config?.privacyUrl&&<a href={config.privacyUrl} target="_blank" rel="noreferrer">Polityka prywatności</a>} {config?.termsUrl&&<a href={config.termsUrl} target="_blank" rel="noreferrer">Regulamin</a>}</span></footer>
  {modal&&<div className="modal-shade" onClick={()=>setModal(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="auth-title" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(false)} aria-label="Zamknij"><X/></button><UserRound className="modal-icon"/><h2 id="auth-title">{register?'Załóż konto kibica':'Dobrze Cię widzieć'}</h2><p>Twoje miejsca pozostają w koszyku. Zaloguj się lub załóż konto, aby dokończyć zakup.</p>{config?.googleLogin&&<button className="google-login" onClick={googleLogin}>Kontynuuj z Google</button>}<form onSubmit={auth}>{register&&<label>Imię<input name="name" autoComplete="given-name" required/></label>}<label>E-mail<input name="email" type="email" autoComplete="email" required autoFocus/></label><label>Hasło<input name="password" type="password" autoComplete={register?'new-password':'current-password'} minLength={register?12:undefined} required/>{register&&<small>Co najmniej 12 znaków.</small>}</label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Chwileczkę…':register?'Utwórz konto':'Zaloguj się'}<ArrowRight size={17}/></button></form><div className="auth-links">{catalog?.registration&&<button onClick={()=>{setRegister(!register);setError('')}}>{register?'Masz konto? Zaloguj się':'Nie masz konta? Zarejestruj się'}</button>}{config?.resetUrl&&<a href={config.resetUrl} target="_blank" rel="noreferrer">Nie pamiętam hasła</a>}</div></section></div>}
 </div>
}

function LayersIcon(){return <Ticket size={48}/>;}

function SeatMap({catalog,normal,reduced,sector,selected,occupied,onSector,onToggle,disabled}:{catalog:Catalog;normal:number;reduced:number;sector:string|null;selected:Record<string,string>;occupied:Record<string,string>;onSector:(s:string)=>void;onToggle:(s:Seat)=>void;disabled:boolean}){
 const [tooltip,setTooltip]=useState<{x:number;y:number}|null>(null);
 const group=catalog.seats.seats.filter(s=>s.sector===sector);const minX=Math.min(...group.map(s=>s.x)),maxX=Math.max(...group.map(s=>s.x));
 const classFor=(s:Seat)=>selected[s.id]?'chosen':occupied[s.id]?'paid':'available';
 if(sector)return <div className="sector-map"><p className="sector-instruction">Wybierz numer miejsca. Rząd 1 znajduje się najbliżej boiska.</p><div className="sector-scroll"><div className="seat-grid" style={{gridTemplateColumns:`25px repeat(${maxX-minX+1}, minmax(27px,1fr))`,minWidth:sector==='C'?630:470}}>{Array.from({length:8},(_,i)=>8-i).map(row=><div className="seat-grid-row" key={row}><span className="row-label">{row}</span>{Array.from({length:maxX-minX+1},(_,i)=>{const s=group.find(s=>s.row===row&&s.x===minX+i);const camera=catalog.seats.cameras.some(c=>c.y===14-row&&c.x===minX+i);return s?<button key={i} className={'seat '+classFor(s)} disabled={disabled||!!occupied[s.id]} aria-pressed={!!selected[s.id]} aria-label={`Sektor ${s.sector}, rząd ${s.row}, miejsce ${s.number}${occupied[s.id]?', niedostępne':''}`} onClick={()=>onToggle(s)}>{s.number}</button>:<span className="gap" key={i}>{camera?<Camera size={15}/>:null}</span>})}</div>)}</div></div><div className="court-edge">BOISKO</div></div>;
 return <div className="overview"><svg viewBox="0 0 900 480" role="img" aria-label="Plan hali: sektory B, C i D nad boiskiem"><defs><pattern id="wood" width="100" height="18" patternUnits="userSpaceOnUse"><rect width="100" height="18" fill="#edf1ef"/><path d="M0 18H100 M50 0V18" stroke="#e4e9e5" strokeWidth="1"/></pattern></defs>{catalog.seats.sectors.map(sec=>{const seats=catalog.seats.seats.filter(s=>s.sector===sec.id);const x=Math.min(...seats.map(s=>s.x))*16;const right=Math.max(...seats.map(s=>s.x))*16;return <g key={sec.id} role="button" tabIndex={0} aria-label={'Powiększ sektor '+sec.id} className="sector-block" onMouseMove={e=>setTooltip({x:Math.min(e.clientX+14,window.innerWidth-230),y:e.clientY+14})} onMouseLeave={()=>setTooltip(null)} onBlur={()=>setTooltip(null)} onClick={()=>onSector(sec.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSector(sec.id)}}}><rect className="sector-bg" x={x-13} y="13" width={right-x+26} height="183" rx="12"/><text x={(x+right)/2} y="37" textAnchor="middle" className="sector-title">SEKTOR {sec.id}</text>{seats.map(s=><circle key={s.id} cx={s.x*16} cy={60+(s.y-6)*15} r="4.2" className={classFor(s)}/>)}<text x={(x+right)/2} y="184" textAnchor="middle" className="sector-count">{seats.filter(s=>!occupied[s.id]).length} wolnych miejsc</text></g>})}<text x="145" y="223" textAnchor="middle" className="bench">ŁAWKA GOŚCI</text><text x="407" y="223" textAnchor="middle" className="bench">STOLIK SĘDZIOWSKI</text><text x="674" y="223" textAnchor="middle" className="bench">ŁAWKA GOSPODARZY</text><g transform="translate(90,245)"><rect width="640" height="215" fill="url(#wood)" rx="10"/><g stroke="#bdc9c0" strokeWidth="2" fill="none"><rect x="13" y="12" width="614" height="190"/><path d="M320 12V202"/><circle cx="320" cy="107" r="35"/><path d="M13 58H107V157H13 M627 58H533V157H627"/><path d="M13 20C190 20 190 194 13 194 M627 20C450 20 450 194 627 194"/><circle cx="40" cy="107" r="8"/><circle cx="600" cy="107" r="8"/></g><image href="./logo.png" x="291" y="78" width="58" height="58"/></g></svg>{tooltip&&<div className="sector-tooltip" style={{left:tooltip.x,top:tooltip.y}}>Normalny <b>{money(normal)}</b><br/>Ulgowy <b>{money(reduced)}</b></div>}</div>
}

function Gate({config,api,onLogin}:{config:Config|null;api:(p:string,b?:unknown)=>Promise<any>;onLogin:()=>void}){
 const [events,setEvents]=useState<Game[]>([]),[eventId,setEventId]=useState(0),[token,setToken]=useState(''),[message,setMessage]=useState(''),[ok,setOk]=useState(false),[camera,setCamera]=useState(false),[busy,setBusy]=useState(false);const video=useRef<HTMLVideoElement>(null),controls=useRef<{stop:()=>void}|null>(null),scanning=useRef(false),cameraEpoch=useRef(0);
 useEffect(()=>{if(config?.user?.gate)api('gate/events').then(es=>{setEvents(es);setEventId(Number(es[0]?.id||0))}).catch(e=>setMessage(e.message));},[config,api]);
 useEffect(()=>()=>{cameraEpoch.current++;controls.current?.stop()},[]);
 function stop(){cameraEpoch.current++;controls.current?.stop();setCamera(false);}
 async function scan(value:string){if(scanning.current||!eventId)return;scanning.current=true;setBusy(true);stop();try{const r=await api('gate/scan',{token:value,event_id:eventId});setOk(true);setMessage(`Wejście przyjęte. Sektor ${r.seat.sector}, rząd ${r.seat.row}, miejsce ${r.seat.number}. ${r.kind==='reduced'?'Bilet ulgowy — sprawdź uprawnienie.':r.kind==='voucher'?'VOUCHER':''}`);setToken('');}catch(e){setOk(false);setMessage((e as Error).message);}finally{setBusy(false);}}
 async function start(){const epoch=++cameraEpoch.current;scanning.current=false;setMessage('');setCamera(true);try{const {BrowserQRCodeReader}=await import('@zxing/browser');const reader=new BrowserQRCodeReader();controls.current=await reader.decodeFromVideoDevice(undefined,video.current!,result=>{if(result&&epoch===cameraEpoch.current)scan(result.getText())});if(scanning.current||epoch!==cameraEpoch.current)controls.current?.stop();}catch{setCamera(false);setOk(false);setMessage('Nie można uruchomić aparatu. Zezwól na dostęp i używaj HTTPS albo wklej kod z czytnika.');}}
 if(!config?.user)return <section className="account"><h1>Panel biletera</h1><p>Zaloguj się na konto obsługi wejścia.</p><button className="primary" onClick={onLogin}>Zaloguj się</button></section>;
 if(!config.user.gate)return <section className="account"><h1>Brak uprawnień biletera</h1><p>Administrator musi przypisać temu kontu rolę „Bileter Decka”.</p></section>;
 return <section className="gate"><h1>Decka · bileter</h1><label>Mecz<select value={eventId} onChange={e=>{stop();setEventId(Number(e.target.value));setMessage('')}}>{events.map(e=><option key={e.id} value={e.id}>{date(e.starts_at)} · {e.opponent}</option>)}</select></label><div className={'scanner-window '+(message?(ok?'success':'failure'):'')}><video ref={video} muted playsInline style={{display:camera?'block':'none'}}/>{!camera&&<div role="status">{message||(busy?'Sprawdzamy…':'Gotowy do skanowania')}</div>}</div><button className="primary" disabled={!eventId||busy} onClick={()=>camera?stop():start()}><Camera size={20}/>{camera?'Zatrzymaj aparat':message?'Skanuj następny':'Skanuj aparatem'}</button><form onSubmit={e=>{e.preventDefault();scanning.current=false;scan(token)}}><label>Kod biletu / czytnik USB<input value={token} onChange={e=>setToken(e.target.value)} placeholder="DK1.… lub DK2.…" required autoComplete="off"/></label><button disabled={busy||!eventId||!token}>Sprawdź i zapisz wejście</button></form></section>
}
