<?php
final class Decka_Admin {
    public static function archive():void {
        if(!current_user_can('manage_options'))wp_die('Brak dostępu.',403);check_admin_referer('decka_archive');global $wpdb;
        $data=['generated_at'=>gmdate('c'),'version'=>DECKA_VERSION,'site'=>home_url(),'settings'=>Decka_DB::settings(),'tables'=>[]];
        foreach(['events','offers','promos','orders','items','inventory','tickets','audit'] as $name)$data['tables'][$name]=$wpdb->get_results('SELECT * FROM '.Decka_DB::table($name),ARRAY_A);
        Decka_DB::audit('archive_download',0,'Pełne archiwum JSON');$json=wp_json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);nocache_headers();header('Content-Type: application/gzip');header('Content-Disposition: attachment; filename="decka-archiwum-'.gmdate('Y-m-d-His').'.json.gz"');echo gzencode($json,9);exit;
    }
    public static function report_pdf():void {
        if(!current_user_can('decka_manage'))wp_die('Brak dostępu.',403);check_admin_referer('decka_report_pdf');global $wpdb;$event=absint($_GET['event']??0);$month=preg_match('/^\d{4}-\d{2}$/',$_GET['month']??'')?$_GET['month']:'';$where=$event?$wpdb->prepare(' AND e.id=%d',$event):($month?$wpdb->prepare(' AND DATE_FORMAT(e.starts_at,"%%Y-%%m")=%s',$month):'');
        $rows=$wpdb->get_results($wpdb->prepare('SELECT e.id,e.opponent,e.starts_at,COUNT(DISTINCT CASE WHEN o.status IN ("paid","free","voucher") THEN t.id END) issued,SUM(o.status="paid" AND i.kind="normal") normal,SUM(o.status="paid" AND i.kind="reduced") reduced,SUM(o.status="free") free_count,SUM(o.status="voucher") vouchers,SUM(t.used_at IS NOT NULL) entered,COALESCE(SUM(CASE WHEN o.status="paid" THEN i.amount ELSE 0 END),0) revenue FROM '.Decka_DB::table('events').' e LEFT JOIN '.Decka_DB::table('items').' i ON i.event_id=e.id LEFT JOIN '.Decka_DB::table('orders').' o ON o.id=i.order_id AND o.mode=%s LEFT JOIN '.Decka_DB::table('tickets').' t ON t.order_id=o.id AND t.event_id=e.id AND t.seat_id=i.seat_id WHERE 1=1'.$where.' GROUP BY e.id ORDER BY e.starts_at',Decka_DB::mode()));
        require_once DECKA_DIR.'vendor/tcpdf/tcpdf.php';$pdf=new TCPDF('L','mm','A4',true,'UTF-8',false);$pdf->setPrintHeader(false);$pdf->setPrintFooter(false);$pdf->SetMargins(12,12,12);$pdf->AddPage();$pdf->SetFont('dejavusans','B',18);$pdf->Cell(0,10,'Raport sprzedaży Decka Pelplin',0,1);$pdf->SetFont('dejavusans','',9);$pdf->Cell(0,7,'Zakres: '.($event?'wybrany mecz':($month?'miesiąc '.$month:'wszystkie mecze')).' · wygenerowano '.wp_date('d.m.Y H:i'),0,1);$headers=['Mecz','Termin','Normalne','Ulgowe','Darmowe','Vouchery','Wydane','Wejścia','Zapełnienie','Przychód'];$widths=[57,31,22,22,22,22,22,22,25,30];$pdf->SetFillColor(25,86,157);$pdf->SetTextColor(255,255,255);$pdf->SetFont('dejavusans','B',7);foreach($headers as $i=>$h)$pdf->Cell($widths[$i],8,$h,1,0,'C',true);$pdf->Ln();$pdf->SetTextColor(23,46,76);$pdf->SetFont('dejavusans','',7);$capacity=count(Decka_DB::seats()['seats']);foreach($rows as $r){$values=[$r->opponent,$r->starts_at?wp_date('d.m.Y H:i',strtotime($r->starts_at.' UTC')):'—',(int)$r->normal,(int)$r->reduced,(int)$r->free_count,(int)$r->vouchers,(int)$r->issued,(int)$r->entered,$capacity?round((int)$r->issued*100/$capacity,1).'%':'—',number_format((int)$r->revenue/100,2,',',' ').' zł'];foreach($values as $i=>$v)$pdf->Cell($widths[$i],8,(string)$v,1,0,$i<2?'L':'C');$pdf->Ln();}Decka_DB::audit('report_pdf',0,wp_json_encode(['event'=>$event,'month'=>$month]));$pdf->Output('raport-decka.pdf','D');exit;
    }
    public static function export():void {
        if(!current_user_can('decka_manage'))wp_die('Brak dostępu.',403);check_admin_referer('decka_stats');global $wpdb;$mode=Decka_DB::mode();$event=absint($_GET['event']??0);
        nocache_headers();header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="Decka-statystyki-'.$mode.'-'.gmdate('Y-m-d').'.csv"');
        $out=fopen('php://output','w');fwrite($out,"\xEF\xBB\xBF");fputcsv($out,['ID meczu','Przeciwnik','Termin UTC','ID zamówienia','Środowisko','Status','E-mail','Sektor','Miejsce','Typ biletu','Kwota przypisana PLN','Data zakupu UTC','Data zapłaty UTC','Wejście UTC'],';','"','');$seats=array_column(Decka_DB::seats()['seats'],null,'id');
        for($offset=0;;$offset+=1000){$rows=$wpdb->get_results($wpdb->prepare('SELECT i.*,e.opponent,e.starts_at,o.mode,o.status,o.email,o.created_at,o.paid_at,t.used_at FROM '.Decka_DB::table('items').' i JOIN '.Decka_DB::table('orders').' o ON o.id=i.order_id JOIN '.Decka_DB::table('events').' e ON e.id=i.event_id LEFT JOIN '.Decka_DB::table('tickets').' t ON t.order_id=i.order_id AND t.event_id=i.event_id AND t.seat_id=i.seat_id WHERE o.mode=%s '.($event?'AND i.event_id='.(int)$event:'').' ORDER BY i.id LIMIT 1000 OFFSET %d',$mode,$offset));if(!$rows)break;
            foreach($rows as $r){$line=[$r->event_id,$r->opponent,$r->starts_at,$r->order_id,$r->mode,$r->status,$r->email,$seats[$r->seat_id]['sector']??'',$r->seat_id,$r->kind,number_format((int)$r->amount/100,2,',',''),$r->created_at,$r->paid_at,$r->used_at];$line=array_map(function($v){$s=(string)$v;return preg_match('/^[=+@\-\t\r\n]/',$s)?"'".$s:$s;},$line);fputcsv($out,$line,';','"','');}
        }fclose($out);exit;
    }
    public static function screens():array{return ['overview'=>'Pulpit','events'=>'Mecze','hall'=>'Plan hali','orders'=>'Zamówienia','tickets'=>'Bilety i vouchery','offers'=>'Mini-karnety','promos'=>'Promocje i kody','fans'=>'Kibice','gate'=>'Obsługa i dostępy','logs'=>'Logi systemowe','reports'=>'Raporty','settings'=>'Ustawienia'];}
    public static function menu():void {
        add_menu_page('Decka Bilety','Decka Bilety','decka_manage','decka-bilety',[self::class,'page'],'dashicons-tickets-alt',30);
        foreach(self::screens() as $key=>$label)add_submenu_page('decka-bilety',$label.' · Decka Bilety',$label,'decka_manage',$key==='overview'?'decka-bilety':'decka-bilety-'.$key,[self::class,'page']);
    }
    public static function page():void {
        if(!current_user_can('decka_manage'))wp_die('Brak dostępu.',403);
        $screen=str_replace('decka-bilety-','',sanitize_key($_GET['page']??''));if(!isset(self::screens()[$screen]))$screen='overview';
        $url=add_query_arg(['action'=>'decka_app','view'=>'admin','screen'=>$screen],admin_url('admin-post.php'));
        echo '<style>#wpcontent{padding-left:0}#wpbody-content{padding-bottom:0}#wpfooter{display:none}.decka-admin-frame{width:100%;height:calc(100vh - 32px);min-height:720px;border:0;display:block}@media(max-width:782px){.decka-admin-frame{height:calc(100vh - 46px)}}</style><iframe class="decka-admin-frame" title="Panel administracyjny Decka Bilety" src="'.esc_url($url).'"></iframe>';
    }
}
