<?php
/** Signed wallet passes. The gate remains the authority for validity and admission. */
final class Decka_Wallet {
    private static function secret(string $key):string {return Decka_Stripe::decrypt(Decka_DB::settings()[$key]??'');}
    public static function enabled(string $type):bool {
        $s=Decka_DB::settings();return $type==='apple'?class_exists('ZipArchive')&&!empty($s['apple_pass_type'])&&!empty($s['apple_team_id'])&&!empty($s['apple_certificate'])&&!empty($s['apple_private_key'])&&!empty($s['apple_wwdr']):!empty($s['google_wallet_issuer'])&&!empty($s['google_wallet_credentials']);
    }
    public static function links(int $order):array {
        $links=[];foreach(Decka_Tickets::documents($order) as $doc)foreach(['apple','google'] as $type)if(self::enabled($type))$links[]=['label'=>($type==='apple'?'Apple Wallet':'Google Wallet').' · miejsce '.$doc['ticket']->seat_id,'url'=>add_query_arg(['action'=>'decka_wallet','order'=>$order,'ticket'=>$doc['ticket']->id,'type'=>$type,'_wpnonce'=>wp_create_nonce('decka_wallet_'.$order)],admin_url('admin-post.php'))];return $links;
    }
    private static function schedule(array $doc):string {return implode("\n",array_map(fn($e)=>$e->opponent.' · '.($e->starts_at?wp_date('d.m.Y H:i',strtotime($e->starts_at.' UTC'),new DateTimeZone('Europe/Warsaw')):'Termin do potwierdzenia'),$doc['events']));}
    public static function apple(array $doc,object $order):string {
        if(!self::enabled('apple'))throw new RuntimeException('Apple Wallet nie jest skonfigurowany.');$s=Decka_DB::settings();$t=$doc['ticket'];$seat=array_column(Decka_DB::seats()['seats'],null,'id')[$t->seat_id];
        $pass=['formatVersion'=>1,'passTypeIdentifier'=>$s['apple_pass_type'],'serialNumber'=>substr(hash('sha256',home_url()),0,12).'-'.$order->mode.'-'.$t->id,'teamIdentifier'=>$s['apple_team_id'],'organizationName'=>'Decka Pelplin','description'=>$doc['package']?'Mini-karnet Decka Pelplin':'Bilet Decka Pelplin','logoText'=>'DECKA PELPLIN','foregroundColor'=>'rgb(255,255,255)','backgroundColor'=>'rgb(25,86,157)','labelColor'=>'rgb(221,235,255)','barcodes'=>[['format'=>'PKBarcodeFormatQR','message'=>$doc['token'],'messageEncoding'=>'iso-8859-1']],'eventTicket'=>['primaryFields'=>[['key'=>'event','label'=>$order->mode==='test'?'TEST — NIEWAŻNY NA MECZ':'DECKA PELPLIN','value'=>$doc['package']?'Mini-karnet':$t->opponent]],'secondaryFields'=>[['key'=>'seat','label'=>'SEKTOR / RZĄD / MIEJSCE','value'=>$seat['sector'].' / '.$seat['row'].' / '.$seat['number']]],'auxiliaryFields'=>[['key'=>'venue','label'=>'HALA','value'=>$t->venue]],'backFields'=>[['key'=>'schedule','label'=>'OBJĘTE MECZE','value'=>self::schedule($doc)],['key'=>'terms','label'=>'WAŻNOŚĆ','value'=>'Jeden kod na wskazane mecze, po jednym wejściu na każdy. Terminy mogą się zmienić. Aktualne dane sprawdź na koncie kibica. Obowiązują ustawowe prawa konsumenta.']]]];
        if(!$doc['package']&&$t->starts_at)$pass['relevantDate']=gmdate('c',strtotime($t->starts_at.' UTC'));
        $dir=sys_get_temp_dir().'/decka-wallet-'.bin2hex(random_bytes(12));if(!mkdir($dir,0700))throw new RuntimeException('Brak katalogu tymczasowego.');
        try{
            file_put_contents($dir.'/pass.json',wp_json_encode($pass,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));
            // WordPress image editor resizes the club asset to Apple's required icon dimensions.
            foreach(['icon.png'=>29,'icon@2x.png'=>58,'icon@3x.png'=>87] as $name=>$size){$editor=wp_get_image_editor(DECKA_DIR.'assets/logo.png');if(is_wp_error($editor))throw new RuntimeException('Serwer nie obsługuje obrazów portfela.');$editor->resize($size,$size,true);$result=$editor->save($dir.'/'.$name,'image/png');if(is_wp_error($result))throw new RuntimeException('Nie można zapisać ikony.');}
            $manifest=[];foreach(['pass.json','icon.png','icon@2x.png','icon@3x.png'] as $name)$manifest[$name]=sha1_file($dir.'/'.$name);file_put_contents($dir.'/manifest.json',wp_json_encode($manifest));file_put_contents($dir.'/wwdr.pem',self::secret('apple_wwdr'));
            $cert=self::secret('apple_certificate');$key=openssl_pkey_get_private(self::secret('apple_private_key'),self::secret('apple_key_password'));if(!$key||!openssl_x509_check_private_key($cert,$key))throw new RuntimeException('Certyfikat Apple i klucz prywatny nie pasują.');
            if(!openssl_pkcs7_sign($dir.'/manifest.json',$dir.'/signed',$cert,$key,[],PKCS7_BINARY|PKCS7_DETACHED,$dir.'/wwdr.pem'))throw new RuntimeException('Nie można podpisać biletu Apple.');
            $signed=file_get_contents($dir.'/signed');if(!preg_match('/Content-Type: application\/x-pkcs7-signature.*?\r?\n\r?\n([A-Za-z0-9+\/=\r\n]+)\r?\n--/s',$signed,$m))throw new RuntimeException('Nieprawidłowy podpis portfela.');$signature=base64_decode(preg_replace('/\s/','',$m[1]),true);if(!$signature)throw new RuntimeException('Pusty podpis portfela.');file_put_contents($dir.'/signature',$signature);
            $zip=new ZipArchive();if($zip->open($dir.'/ticket.pkpass',ZipArchive::CREATE)!==true)throw new RuntimeException('Nie można utworzyć portfela.');foreach(array_merge(array_keys($manifest),['manifest.json','signature']) as $name)$zip->addFile($dir.'/'.$name,$name);$zip->close();return file_get_contents($dir.'/ticket.pkpass');
        }finally{foreach(glob($dir.'/*') as $file)unlink($file);rmdir($dir);}
    }
    public static function google(array $doc,object $order):string {
        if(!self::enabled('google'))throw new RuntimeException('Google Wallet nie jest skonfigurowany.');$s=Decka_DB::settings();$credentials=json_decode(self::secret('google_wallet_credentials'),true);if(empty($credentials['client_email'])||empty($credentials['private_key']))throw new RuntimeException('Nieprawidłowy plik konta usługi Google.');$t=$doc['ticket'];$prefix=$s['google_wallet_issuer'];$namespace=substr(hash('sha256',home_url()),0,12);$class=$prefix.'.decka_'.$namespace;
        $payload=['iss'=>$credentials['client_email'],'aud'=>'google','typ'=>'savetowallet','iat'=>time(),'origins'=>[home_url()],'payload'=>['genericClasses'=>[['id'=>$class]],'genericObjects'=>[['id'=>$prefix.'.'.$namespace.'_'.$order->mode.'_'.$t->id,'classId'=>$class,'state'=>'ACTIVE','hexBackgroundColor'=>'#19569d','cardTitle'=>['defaultValue'=>['language'=>'pl-PL','value'=>'Decka Pelplin']],'header'=>['defaultValue'=>['language'=>'pl-PL','value'=>($order->mode==='test'?'TEST · ':'').($doc['package']?'Mini-karnet':$t->opponent)]],'subheader'=>['defaultValue'=>['language'=>'pl-PL','value'=>'Miejsce '.$t->seat_id]],'barcode'=>['type'=>'QR_CODE','value'=>$doc['token']],'textModulesData'=>[['id'=>'schedule','header'=>'Mecze i terminy','body'=>self::schedule($doc)],['id'=>'venue','header'=>'Hala','body'=>$t->venue],['id'=>'validity','header'=>'Ważność','body'=>'Jedno wejście na każdy objęty mecz. Terminy mogą się zmienić; aktualne dane na koncie kibica. Zachowujesz ustawowe prawa konsumenta.']]]]]];
        $b64=fn($v)=>rtrim(strtr(base64_encode($v),'+/','-_'),'=');$unsigned=$b64(wp_json_encode(['alg'=>'RS256','typ'=>'JWT'])).'.'.$b64(wp_json_encode($payload));if(!openssl_sign($unsigned,$signature,$credentials['private_key'],OPENSSL_ALGO_SHA256))throw new RuntimeException('Nie można podpisać biletu Google.');return 'https://pay.google.com/gp/v/save/'.$unsigned.'.'.$b64($signature);
    }
    public static function download():void {
        $id=absint($_GET['order']??0);check_admin_referer('decka_wallet_'.$id);$order=Decka_Service::order($id);if(!$order||!get_current_user_id()||((int)$order->user_id!==get_current_user_id()&&!current_user_can('decka_manage')))wp_die('Brak dostępu.',403);
        try{$doc=null;foreach(Decka_Tickets::documents($id) as $candidate)if((int)$candidate['ticket']->id===absint($_GET['ticket']??0))$doc=$candidate;if(!$doc)throw new RuntimeException('Nie znaleziono biletu.');nocache_headers();header('Referrer-Policy: no-referrer');if(($_GET['type']??'')==='google'){wp_redirect(self::google($doc,$order));exit;}$bytes=self::apple($doc,$order);header('Content-Type: application/vnd.apple.pkpass');header('Content-Disposition: attachment; filename="Decka-'.$doc['ticket']->id.'.pkpass"');header('X-Content-Type-Options: nosniff');echo $bytes;}catch(Throwable $e){wp_die(esc_html($e->getMessage()));}exit;
    }
}
